/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.ec.com.donbosquito.vista.moduloPersona;

import edu.ec.com.donbosquito.controlador.moduloPersona.ControladorDocente;

/**
 *
 * @author fernandosanchez
 */
public class DocenteVista extends javax.swing.JFrame {
    
    DocenteBuscar docenteBuscar = new DocenteBuscar();
    DocenteCrear docenteCrear = new DocenteCrear();
    DocenteEliminar docenteEliminar = new DocenteEliminar();
    DocenteModificar docenteModificar = new DocenteModificar();
    ControladorDocente controladorDocente = new ControladorDocente();
    DocenteListar docenteListar = new DocenteListar(controladorDocente);

    /** Creates new form Docente */
    public DocenteVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        jpContenedorEstudiante.add(docenteCrear);
        docenteBuscar.setVisible(false);
        docenteEliminar.setVisible(false);   
        docenteModificar.setVisible(false);
        docenteListar.setVisible(false);
        docenteCrear.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpContenido = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbMenu = new javax.swing.JPanel();
        jbCrearDocente = new javax.swing.JButton();
        jbBuscarDocente = new javax.swing.JButton();
        jbModificarDocente = new javax.swing.JButton();
        jbListatDocente = new javax.swing.JButton();
        jbVolverDocente = new javax.swing.JButton();
        jbEliminarDocente = new javax.swing.JButton();
        jpContenedorEstudiante = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpContenido.setBackground(new java.awt.Color(102, 102, 102));

        jpTitulo.setBackground(new java.awt.Color(51, 51, 51));
        jpTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("UNIDAD EDUCATIVA DON BOSQUITO");

        javax.swing.GroupLayout jpTituloLayout = new javax.swing.GroupLayout(jpTitulo);
        jpTitulo.setLayout(jpTituloLayout);
        jpTituloLayout.setHorizontalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloLayout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel1)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jpTituloLayout.setVerticalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbMenu.setBackground(new java.awt.Color(51, 51, 51));

        jbCrearDocente.setBackground(new java.awt.Color(51, 51, 51));
        jbCrearDocente.setForeground(new java.awt.Color(204, 204, 204));
        jbCrearDocente.setText("Crear Docente");
        jbCrearDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearDocenteActionPerformed(evt);
            }
        });

        jbBuscarDocente.setBackground(new java.awt.Color(51, 51, 51));
        jbBuscarDocente.setForeground(new java.awt.Color(204, 204, 204));
        jbBuscarDocente.setText("Buscar Docente");
        jbBuscarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarDocenteActionPerformed(evt);
            }
        });

        jbModificarDocente.setBackground(new java.awt.Color(51, 51, 51));
        jbModificarDocente.setForeground(new java.awt.Color(204, 204, 204));
        jbModificarDocente.setText("Modificar Docente");
        jbModificarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarDocenteActionPerformed(evt);
            }
        });

        jbListatDocente.setBackground(new java.awt.Color(51, 51, 51));
        jbListatDocente.setForeground(new java.awt.Color(204, 204, 204));
        jbListatDocente.setText("Listar Docente");
        jbListatDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListatDocenteActionPerformed(evt);
            }
        });

        jbVolverDocente.setBackground(new java.awt.Color(51, 51, 51));
        jbVolverDocente.setForeground(new java.awt.Color(204, 204, 204));
        jbVolverDocente.setText("Volver");

        jbEliminarDocente.setBackground(new java.awt.Color(51, 51, 51));
        jbEliminarDocente.setForeground(new java.awt.Color(204, 204, 204));
        jbEliminarDocente.setText("Eliminar Docente");
        jbEliminarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarDocenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jbMenuLayout = new javax.swing.GroupLayout(jbMenu);
        jbMenu.setLayout(jbMenuLayout);
        jbMenuLayout.setHorizontalGroup(
            jbMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCrearDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbBuscarDocente, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jbModificarDocente, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jbListatDocente, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jbVolverDocente, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jbEliminarDocente, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addContainerGap())
        );
        jbMenuLayout.setVerticalGroup(
            jbMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCrearDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBuscarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbModificarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbEliminarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbListatDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbVolverDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpContenedorEstudiante.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jpContenidoLayout = new javax.swing.GroupLayout(jpContenido);
        jpContenido.setLayout(jpContenidoLayout);
        jpContenidoLayout.setHorizontalGroup(
            jpContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpContenedorEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpContenidoLayout.setVerticalGroup(
            jpContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenidoLayout.createSequentialGroup()
                .addComponent(jpTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpContenedorEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarDocenteActionPerformed
        // TODO add your handling code here:
        docenteBuscar.setVisible(true);
        docenteCrear.setVisible(false);
        docenteEliminar.setVisible(false);
        docenteModificar.setVisible(false);
        docenteListar.setVisible(false);
        jpContenedorEstudiante.add(docenteBuscar);
        jpContenedorEstudiante.validate();
    }//GEN-LAST:event_jbBuscarDocenteActionPerformed

    private void jbCrearDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearDocenteActionPerformed
        // TODO add your handling code here:
        docenteCrear.setVisible(true);
        docenteBuscar.setVisible(false);
        docenteEliminar.setVisible(false);
        docenteModificar.setVisible(false);
        docenteListar.setVisible(false);
        jpContenedorEstudiante.add(docenteCrear);
        jpContenedorEstudiante.validate();
    }//GEN-LAST:event_jbCrearDocenteActionPerformed

    private void jbEliminarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarDocenteActionPerformed
        // TODO add your handling code here:
        docenteCrear.setVisible(false);
        docenteBuscar.setVisible(false);
        docenteEliminar.setVisible(true);
        docenteModificar.setVisible(false);
        docenteListar.setVisible(false);
        jpContenedorEstudiante.add(docenteEliminar);
        jpContenedorEstudiante.validate();
    }//GEN-LAST:event_jbEliminarDocenteActionPerformed

    private void jbModificarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarDocenteActionPerformed
        // TODO add your handling code here:
        docenteCrear.setVisible(false);
        docenteBuscar.setVisible(false);
        docenteEliminar.setVisible(false);
        docenteModificar.setVisible(true);
        docenteListar.setVisible(false);
        jpContenedorEstudiante.add(docenteModificar);
        jpContenedorEstudiante.validate();
    }//GEN-LAST:event_jbModificarDocenteActionPerformed

    private void jbListatDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListatDocenteActionPerformed
        // TODO add your handling code here:
        docenteCrear.setVisible(false);
        docenteBuscar.setVisible(false);
        docenteEliminar.setVisible(false);
        docenteModificar.setVisible(false);
        docenteListar.setVisible(true);
        jpContenedorEstudiante.add(docenteListar);
        jpContenedorEstudiante.validate();
    }//GEN-LAST:event_jbListatDocenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DocenteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DocenteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DocenteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocenteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DocenteVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbBuscarDocente;
    private javax.swing.JButton jbCrearDocente;
    private javax.swing.JButton jbEliminarDocente;
    private javax.swing.JButton jbListatDocente;
    private javax.swing.JPanel jbMenu;
    private javax.swing.JButton jbModificarDocente;
    private javax.swing.JButton jbVolverDocente;
    private javax.swing.JPanel jpContenedorEstudiante;
    private javax.swing.JPanel jpContenido;
    private javax.swing.JPanel jpTitulo;
    // End of variables declaration//GEN-END:variables

}
