package edu.ec.com.donbosquito.vista.moduloPersona;

import edu.ec.com.donbosquito.controlador.moduloPersona.ControladorDocente;
import edu.ec.com.donbosquito.modelo.moduloPersona.Docente;
import edu.ec.com.donbosquito.modelo.moduloPersona.Estudiante;
import edu.ec.com.donbosquito.modelo.moduloPersona.Persona;
import edu.ec.com.donbosquito.modelo.moduloPersona.Representante;
import java.text.ParseException;
import java.text.SimpleDateFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fernandosanchez
 */
public class DocenteModificar extends javax.swing.JPanel {
    
    ControladorDocente controladorDocente = new ControladorDocente();
    String aux;
    

    /**
     * Creates new form NewJPanel
     */
    public DocenteModificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEliminarDocente = new javax.swing.JPanel();
        jlCedulaModificar = new javax.swing.JLabel();
        jlNombreModificar = new javax.swing.JLabel();
        txtCedulaModificar = new javax.swing.JTextField();
        txtNombreModificar = new javax.swing.JTextField();
        jLApellidosModificar = new javax.swing.JLabel();
        txtApellidosModificar = new javax.swing.JTextField();
        jlDireccionModificar = new javax.swing.JLabel();
        txtDireccionModificar = new javax.swing.JTextField();
        jlTelefonoModificar = new javax.swing.JLabel();
        txtTelefonoModificar = new javax.swing.JTextField();
        jlCorreoModificar = new javax.swing.JLabel();
        txtCorreoModificar = new javax.swing.JTextField();
        jlTituloModificar = new javax.swing.JLabel();
        txtTituloModificar = new javax.swing.JTextField();
        jbModificar = new javax.swing.JButton();
        jbLimpiarModificar = new javax.swing.JButton();
        jlBuscarModificar = new javax.swing.JLabel();
        txtBuscarModificar = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();

        jPanelEliminarDocente.setBackground(new java.awt.Color(51, 51, 51));

        jlCedulaModificar.setForeground(new java.awt.Color(204, 204, 204));
        jlCedulaModificar.setText("Cédula:");

        jlNombreModificar.setForeground(new java.awt.Color(204, 204, 204));
        jlNombreModificar.setText("Nombre:");

        txtCedulaModificar.setBackground(new java.awt.Color(153, 153, 153));

        txtNombreModificar.setBackground(new java.awt.Color(153, 153, 153));
        txtNombreModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreModificarActionPerformed(evt);
            }
        });

        jLApellidosModificar.setBackground(new java.awt.Color(204, 204, 204));
        jLApellidosModificar.setForeground(new java.awt.Color(204, 204, 204));
        jLApellidosModificar.setText("Apellidos:");

        txtApellidosModificar.setBackground(new java.awt.Color(153, 153, 153));

        jlDireccionModificar.setForeground(new java.awt.Color(204, 204, 204));
        jlDireccionModificar.setText("Dirección:");

        txtDireccionModificar.setBackground(new java.awt.Color(153, 153, 153));

        jlTelefonoModificar.setForeground(new java.awt.Color(204, 204, 204));
        jlTelefonoModificar.setText("Teléfono:");

        txtTelefonoModificar.setBackground(new java.awt.Color(153, 153, 153));

        jlCorreoModificar.setForeground(new java.awt.Color(204, 204, 204));
        jlCorreoModificar.setText("Correo:");

        txtCorreoModificar.setBackground(new java.awt.Color(153, 153, 153));

        jlTituloModificar.setForeground(new java.awt.Color(204, 204, 204));
        jlTituloModificar.setText("Titulo:");

        txtTituloModificar.setBackground(new java.awt.Color(153, 153, 153));

        jbModificar.setBackground(new java.awt.Color(51, 51, 51));
        jbModificar.setForeground(new java.awt.Color(204, 204, 204));
        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbLimpiarModificar.setBackground(new java.awt.Color(51, 51, 51));
        jbLimpiarModificar.setForeground(new java.awt.Color(204, 204, 204));
        jbLimpiarModificar.setText("Limpiar");
        jbLimpiarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarModificarActionPerformed(evt);
            }
        });

        jlBuscarModificar.setForeground(new java.awt.Color(204, 204, 204));
        jlBuscarModificar.setText("Ingresar Cédula:");

        txtBuscarModificar.setBackground(new java.awt.Color(153, 153, 153));

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEliminarDocenteLayout = new javax.swing.GroupLayout(jPanelEliminarDocente);
        jPanelEliminarDocente.setLayout(jPanelEliminarDocenteLayout);
        jPanelEliminarDocenteLayout.setHorizontalGroup(
            jPanelEliminarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarDocenteLayout.createSequentialGroup()
                .addGroup(jPanelEliminarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEliminarDocenteLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(jPanelEliminarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCedulaModificar)
                            .addComponent(jlNombreModificar)
                            .addComponent(jLApellidosModificar)
                            .addComponent(jlDireccionModificar)
                            .addComponent(jlTelefonoModificar)
                            .addComponent(jlCorreoModificar)
                            .addComponent(jlTituloModificar)
                            .addComponent(jlBuscarModificar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEliminarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedulaModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtNombreModificar)
                            .addComponent(txtApellidosModificar)
                            .addComponent(txtDireccionModificar)
                            .addComponent(txtTelefonoModificar)
                            .addComponent(txtCorreoModificar)
                            .addComponent(txtTituloModificar)
                            .addComponent(txtBuscarModificar))
                        .addGap(44, 44, 44)
                        .addComponent(jbBuscar))
                    .addGroup(jPanelEliminarDocenteLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jbLimpiarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanelEliminarDocenteLayout.setVerticalGroup(
            jPanelEliminarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarDocenteLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelEliminarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBuscarModificar)
                    .addComponent(txtBuscarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanelEliminarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCedulaModificar)
                    .addComponent(txtCedulaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEliminarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNombreModificar)
                    .addComponent(txtNombreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEliminarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLApellidosModificar)
                    .addComponent(txtApellidosModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEliminarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDireccionModificar)
                    .addComponent(txtDireccionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEliminarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTelefonoModificar)
                    .addComponent(txtTelefonoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEliminarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCorreoModificar)
                    .addComponent(txtCorreoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEliminarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTituloModificar)
                    .addComponent(txtTituloModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelEliminarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbModificar)
                    .addComponent(jbLimpiarModificar))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelEliminarDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelEliminarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimpiarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarModificarActionPerformed
        // TODO add your handling code here:
        limpiar();
        
    }//GEN-LAST:event_jbLimpiarModificarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        
        modificarDocente();
        
    }//GEN-LAST:event_jbModificarActionPerformed

    private void txtNombreModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreModificarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        buscarDocente();
    }//GEN-LAST:event_jbBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLApellidosModificar;
    private javax.swing.JPanel jPanelEliminarDocente;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbLimpiarModificar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JLabel jlBuscarModificar;
    private javax.swing.JLabel jlCedulaModificar;
    private javax.swing.JLabel jlCorreoModificar;
    private javax.swing.JLabel jlDireccionModificar;
    private javax.swing.JLabel jlNombreModificar;
    private javax.swing.JLabel jlTelefonoModificar;
    private javax.swing.JLabel jlTituloModificar;
    private javax.swing.JTextField txtApellidosModificar;
    private javax.swing.JTextField txtBuscarModificar;
    private javax.swing.JTextField txtCedulaModificar;
    private javax.swing.JTextField txtCorreoModificar;
    private javax.swing.JTextField txtDireccionModificar;
    private javax.swing.JTextField txtNombreModificar;
    private javax.swing.JTextField txtTelefonoModificar;
    private javax.swing.JTextField txtTituloModificar;
    // End of variables declaration//GEN-END:variables
    
    void buscarDocente(){
        Persona persona = new Persona(0, "", "", "", "", "", "") {
        };
        Docente docente = new Docente(0, "", persona, 0, "", "", "", "", "", "");
        docente = controladorDocente.buscarDocenteCedula(txtBuscarModificar.getText());
        txtCedulaModificar.setText(docente.getCedula());
        txtNombreModificar.setText(docente.getNombre());
        txtApellidosModificar.setText(docente.getApellido());
        txtDireccionModificar.setText(docente.getDireccion());
        txtTelefonoModificar.setText(docente.getTelefono());
        txtCorreoModificar.setText(docente.getCorreo());
        txtTituloModificar.setText(docente.getTituloDocente());
        aux = txtBuscarModificar.getText();
        txtBuscarModificar.setText("");   
    }
    
    void modificarDocente(){
        Persona persona = new Persona(0, "", "", "", "", "", "") {
        };
        Docente docente = new Docente(0, "", persona, 0, "", "", "", "", "", "");
        Representante representante = new Representante(0, "", persona, 0, "", "", "", "", "", "");
        Estudiante estudiante = new Estudiante(0, ParseFecha("0/0/0"), 0, ParseFecha("0/0/0"), persona, representante, 0, "", "", "", "", "", "");
        docente = controladorDocente.buscarDocenteCedula(aux); 
        
        docente.setCedula(txtCedulaModificar.getText());
        docente.setNombre(txtNombreModificar.getText());
        docente.setApellido(txtApellidosModificar.getText());
        docente.setDireccion(txtDireccionModificar.getText());
        docente.setTelefono(txtTelefonoModificar.getText());
        docente.setCorreo(txtCorreoModificar.getText());
        docente.setTituloDocente(txtTituloModificar.getText());
        docente.setCodigoPersona(docente.getCodigoPersona());
        docente.setCodigoDocente(docente.getCodigoDocente());
        docente.setPersona(docente);

        controladorDocente.modificarUsuario(estudiante, docente, representante, persona);
        limpiar();
    }
    
    void limpiar(){
        txtBuscarModificar.setText("");
        txtCedulaModificar.setText("");
        txtNombreModificar.setText("");
        txtApellidosModificar.setText("");
        txtDireccionModificar.setText("");
        txtTelefonoModificar.setText("");
        txtCorreoModificar.setText("");
        txtTituloModificar.setText("");
    }
    
    public static java.util.Date ParseFecha(String fecha) {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date fechaDate = null;
        try {
            fechaDate = formato.parse(fecha);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        return fechaDate;
    }
}
