package edu.ec.com.donbosquito.vista.moduloPersona;

import edu.ec.com.donbosquito.controlador.moduloPersona.ControladorDocente;
import edu.ec.com.donbosquito.modelo.moduloPersona.Docente;
import edu.ec.com.donbosquito.modelo.moduloPersona.Persona;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fernandosanchez
 */
public class DocenteBuscar extends javax.swing.JPanel {
    
    ControladorDocente controladorDocente = new ControladorDocente();
    

    /**
     * Creates new form NewJPanel
     */
    public DocenteBuscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBuscarDocente = new javax.swing.JPanel();
        jlCedulaBuscar = new javax.swing.JLabel();
        jlNombreBuscar = new javax.swing.JLabel();
        txtCedulaBuscar = new javax.swing.JTextField();
        txtNombreBuscar = new javax.swing.JTextField();
        jLApellidosBuscar = new javax.swing.JLabel();
        txtApellidosBuscar = new javax.swing.JTextField();
        jlDireccionBuscar = new javax.swing.JLabel();
        txtDireccionBuscar = new javax.swing.JTextField();
        jlTelefonoBuscar = new javax.swing.JLabel();
        txtTelefonoBuscar = new javax.swing.JTextField();
        jlCorreoBuscar = new javax.swing.JLabel();
        txtCorreoBuscar = new javax.swing.JTextField();
        jlTituloBuscar = new javax.swing.JLabel();
        txtTituloBuscar = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jbLimpiarBuscar = new javax.swing.JButton();
        jlBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        jPanelBuscarDocente.setBackground(new java.awt.Color(51, 51, 51));

        jlCedulaBuscar.setForeground(new java.awt.Color(204, 204, 204));
        jlCedulaBuscar.setText("Cédula:");

        jlNombreBuscar.setForeground(new java.awt.Color(204, 204, 204));
        jlNombreBuscar.setText("Nombre:");

        txtCedulaBuscar.setBackground(new java.awt.Color(153, 153, 153));

        txtNombreBuscar.setBackground(new java.awt.Color(153, 153, 153));
        txtNombreBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBuscarActionPerformed(evt);
            }
        });

        jLApellidosBuscar.setBackground(new java.awt.Color(204, 204, 204));
        jLApellidosBuscar.setForeground(new java.awt.Color(204, 204, 204));
        jLApellidosBuscar.setText("Apellidos:");

        txtApellidosBuscar.setBackground(new java.awt.Color(153, 153, 153));

        jlDireccionBuscar.setForeground(new java.awt.Color(204, 204, 204));
        jlDireccionBuscar.setText("Dirección:");

        txtDireccionBuscar.setBackground(new java.awt.Color(153, 153, 153));

        jlTelefonoBuscar.setForeground(new java.awt.Color(204, 204, 204));
        jlTelefonoBuscar.setText("Teléfono:");

        txtTelefonoBuscar.setBackground(new java.awt.Color(153, 153, 153));

        jlCorreoBuscar.setForeground(new java.awt.Color(204, 204, 204));
        jlCorreoBuscar.setText("Correo:");

        txtCorreoBuscar.setBackground(new java.awt.Color(153, 153, 153));

        jlTituloBuscar.setForeground(new java.awt.Color(204, 204, 204));
        jlTituloBuscar.setText("Titulo:");

        txtTituloBuscar.setBackground(new java.awt.Color(153, 153, 153));

        jbBuscar.setBackground(new java.awt.Color(51, 51, 51));
        jbBuscar.setForeground(new java.awt.Color(204, 204, 204));
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbLimpiarBuscar.setBackground(new java.awt.Color(51, 51, 51));
        jbLimpiarBuscar.setForeground(new java.awt.Color(204, 204, 204));
        jbLimpiarBuscar.setText("Limpiar");
        jbLimpiarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarBuscarActionPerformed(evt);
            }
        });

        jlBuscar.setForeground(new java.awt.Color(204, 204, 204));
        jlBuscar.setText("Ingresar Cédula:");

        txtBuscar.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanelBuscarDocenteLayout = new javax.swing.GroupLayout(jPanelBuscarDocente);
        jPanelBuscarDocente.setLayout(jPanelBuscarDocenteLayout);
        jPanelBuscarDocenteLayout.setHorizontalGroup(
            jPanelBuscarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarDocenteLayout.createSequentialGroup()
                .addGroup(jPanelBuscarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarDocenteLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(jPanelBuscarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCedulaBuscar)
                            .addComponent(jlNombreBuscar)
                            .addComponent(jLApellidosBuscar)
                            .addComponent(jlDireccionBuscar)
                            .addComponent(jlTelefonoBuscar)
                            .addComponent(jlCorreoBuscar)
                            .addComponent(jlTituloBuscar)
                            .addComponent(jlBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBuscarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedulaBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtNombreBuscar)
                            .addComponent(txtApellidosBuscar)
                            .addComponent(txtDireccionBuscar)
                            .addComponent(txtTelefonoBuscar)
                            .addComponent(txtCorreoBuscar)
                            .addComponent(txtTituloBuscar)
                            .addComponent(txtBuscar)))
                    .addGroup(jPanelBuscarDocenteLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jbLimpiarBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanelBuscarDocenteLayout.setVerticalGroup(
            jPanelBuscarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarDocenteLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelBuscarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCedulaBuscar)
                    .addComponent(txtCedulaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNombreBuscar)
                    .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLApellidosBuscar)
                    .addComponent(txtApellidosBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDireccionBuscar)
                    .addComponent(txtDireccionBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTelefonoBuscar)
                    .addComponent(txtTelefonoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCorreoBuscar)
                    .addComponent(txtCorreoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTituloBuscar)
                    .addComponent(txtTituloBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelBuscarDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscar)
                    .addComponent(jbLimpiarBuscar))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelBuscarDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelBuscarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimpiarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarBuscarActionPerformed
        // TODO add your handling code here:
        limpiar();
        
    }//GEN-LAST:event_jbLimpiarBuscarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        
        buscarDocente();
        
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void txtNombreBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLApellidosBuscar;
    private javax.swing.JPanel jPanelBuscarDocente;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbLimpiarBuscar;
    private javax.swing.JLabel jlBuscar;
    private javax.swing.JLabel jlCedulaBuscar;
    private javax.swing.JLabel jlCorreoBuscar;
    private javax.swing.JLabel jlDireccionBuscar;
    private javax.swing.JLabel jlNombreBuscar;
    private javax.swing.JLabel jlTelefonoBuscar;
    private javax.swing.JLabel jlTituloBuscar;
    private javax.swing.JTextField txtApellidosBuscar;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCedulaBuscar;
    private javax.swing.JTextField txtCorreoBuscar;
    private javax.swing.JTextField txtDireccionBuscar;
    private javax.swing.JTextField txtNombreBuscar;
    private javax.swing.JTextField txtTelefonoBuscar;
    private javax.swing.JTextField txtTituloBuscar;
    // End of variables declaration//GEN-END:variables
    void buscarDocente(){
        Persona persona = new Persona(0, "", "", "", "", "", "") {
        };
        Docente docente = new Docente(0, "", persona, 0, "", "", "", "", "", "");
        docente = controladorDocente.buscarDocenteCedula(txtBuscar.getText());
        txtCedulaBuscar.setText(docente.getCedula());
        txtNombreBuscar.setText(docente.getNombre());
        txtApellidosBuscar.setText(docente.getApellido());
        txtDireccionBuscar.setText(docente.getDireccion());
        txtTelefonoBuscar.setText(docente.getTelefono());
        txtCorreoBuscar.setText(docente.getCorreo());
        txtTituloBuscar.setText(docente.getTituloDocente());
        txtBuscar.setText("");   
    }
    
    void limpiar(){
        txtBuscar.setText("");
        txtCedulaBuscar.setText("");
        txtNombreBuscar.setText("");
        txtApellidosBuscar.setText("");
        txtDireccionBuscar.setText("");
        txtTelefonoBuscar.setText("");
        txtCorreoBuscar.setText("");
        txtTituloBuscar.setText("");
    }
}
