/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.ec.com.donbosquito.vista.moduloPersona;

import edu.ec.com.donbosquito.controlador.moduloPersona.ControladorDocente;
import edu.ec.com.donbosquito.controlador.moduloPersona.ControladorEstudiante;

/**
 *
 * @author fernandosanchez
 */
public class EstudianteVista extends javax.swing.JFrame {
    
    EstudianteCrear estudianteCrear = new EstudianteCrear();
    EstudianteBuscar estudianteBuscar = new EstudianteBuscar();
    EstudianteEliminar estudianteEliminar = new EstudianteEliminar();
    EstudianteModificar estudianteModificar = new EstudianteModificar();
    ControladorEstudiante controladorEstudiante = new ControladorEstudiante();
    EstudianteListar estudianteListar = new EstudianteListar(controladorEstudiante);

    /** Creates new form Docente */
    public EstudianteVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        jpContenedorEstudiante.add(estudianteCrear);
        estudianteBuscar.setVisible(false);
        estudianteEliminar.setVisible(false);   
        estudianteModificar.setVisible(false);
        estudianteListar.setVisible(false);
        estudianteCrear.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpContenido = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbMenu = new javax.swing.JPanel();
        jbCrearEstudiante = new javax.swing.JButton();
        jbBuscarEstudiante = new javax.swing.JButton();
        jbModificarEstudiante = new javax.swing.JButton();
        jbListatEstudiante = new javax.swing.JButton();
        jbVolverEstudiante = new javax.swing.JButton();
        jbEliminarEstudiante = new javax.swing.JButton();
        jpContenedorEstudiante = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpContenido.setBackground(new java.awt.Color(102, 102, 102));

        jpTitulo.setBackground(new java.awt.Color(51, 51, 51));
        jpTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("UNIDAD EDUCATIVA DON BOSQUITO");

        javax.swing.GroupLayout jpTituloLayout = new javax.swing.GroupLayout(jpTitulo);
        jpTitulo.setLayout(jpTituloLayout);
        jpTituloLayout.setHorizontalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloLayout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel1)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jpTituloLayout.setVerticalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbMenu.setBackground(new java.awt.Color(51, 51, 51));

        jbCrearEstudiante.setBackground(new java.awt.Color(51, 51, 51));
        jbCrearEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jbCrearEstudiante.setText("Crear Estudiante");
        jbCrearEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearEstudianteActionPerformed(evt);
            }
        });

        jbBuscarEstudiante.setBackground(new java.awt.Color(51, 51, 51));
        jbBuscarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jbBuscarEstudiante.setText("Buscar Estudiante");
        jbBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarEstudianteActionPerformed(evt);
            }
        });

        jbModificarEstudiante.setBackground(new java.awt.Color(51, 51, 51));
        jbModificarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jbModificarEstudiante.setText("Modificar Estudiante");
        jbModificarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarEstudianteActionPerformed(evt);
            }
        });

        jbListatEstudiante.setBackground(new java.awt.Color(51, 51, 51));
        jbListatEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jbListatEstudiante.setText("Listar Estudiante");
        jbListatEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListatEstudianteActionPerformed(evt);
            }
        });

        jbVolverEstudiante.setBackground(new java.awt.Color(51, 51, 51));
        jbVolverEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jbVolverEstudiante.setText("Volver");

        jbEliminarEstudiante.setBackground(new java.awt.Color(51, 51, 51));
        jbEliminarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jbEliminarEstudiante.setText("Eliminar Estudiante");
        jbEliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jbMenuLayout = new javax.swing.GroupLayout(jbMenu);
        jbMenu.setLayout(jbMenuLayout);
        jbMenuLayout.setHorizontalGroup(
            jbMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCrearEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbBuscarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbModificarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbListatEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbVolverEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbEliminarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jbMenuLayout.setVerticalGroup(
            jbMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCrearEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbModificarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbListatEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbVolverEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpContenedorEstudiante.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jpContenidoLayout = new javax.swing.GroupLayout(jpContenido);
        jpContenido.setLayout(jpContenidoLayout);
        jpContenidoLayout.setHorizontalGroup(
            jpContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpContenedorEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpContenidoLayout.setVerticalGroup(
            jpContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenidoLayout.createSequentialGroup()
                .addComponent(jpTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpContenedorEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarEstudianteActionPerformed
        // TODO add your handling code here:
        estudianteBuscar.setVisible(true);
        estudianteCrear.setVisible(false);
        estudianteEliminar.setVisible(false);
        estudianteModificar.setVisible(false);
        estudianteListar.setVisible(false);
        jpContenedorEstudiante.add(estudianteBuscar);
        jpContenedorEstudiante.validate();
    }//GEN-LAST:event_jbBuscarEstudianteActionPerformed

    private void jbCrearEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearEstudianteActionPerformed
        // TODO add your handling code here:
        estudianteCrear.setVisible(true);
        estudianteBuscar.setVisible(false);
        estudianteEliminar.setVisible(false);
        estudianteModificar.setVisible(false);
        estudianteListar.setVisible(false);
        jpContenedorEstudiante.add(estudianteCrear);
        jpContenedorEstudiante.validate();
    }//GEN-LAST:event_jbCrearEstudianteActionPerformed

    private void jbEliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarEstudianteActionPerformed
        // TODO add your handling code here:
        estudianteCrear.setVisible(false);
        estudianteBuscar.setVisible(false);
        estudianteEliminar.setVisible(true);
        estudianteModificar.setVisible(false);
        estudianteListar.setVisible(false);
        jpContenedorEstudiante.add(estudianteEliminar);
        jpContenedorEstudiante.validate();
    }//GEN-LAST:event_jbEliminarEstudianteActionPerformed

    private void jbModificarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarEstudianteActionPerformed
        // TODO add your handling code here:
        estudianteCrear.setVisible(false);
        estudianteBuscar.setVisible(false);
        estudianteEliminar.setVisible(false);
        estudianteModificar.setVisible(true);
        estudianteListar.setVisible(false);
        jpContenedorEstudiante.add(estudianteModificar);
        jpContenedorEstudiante.validate();
    }//GEN-LAST:event_jbModificarEstudianteActionPerformed

    private void jbListatEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListatEstudianteActionPerformed
        // TODO add your handling code here:
        estudianteCrear.setVisible(false);
        estudianteBuscar.setVisible(false);
        estudianteEliminar.setVisible(false);
        estudianteModificar.setVisible(false);
        estudianteListar.setVisible(true);
        jpContenedorEstudiante.add(estudianteListar);
        jpContenedorEstudiante.validate();
    }//GEN-LAST:event_jbListatEstudianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudianteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudianteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudianteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudianteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudianteVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbBuscarEstudiante;
    private javax.swing.JButton jbCrearEstudiante;
    private javax.swing.JButton jbEliminarEstudiante;
    private javax.swing.JButton jbListatEstudiante;
    private javax.swing.JPanel jbMenu;
    private javax.swing.JButton jbModificarEstudiante;
    private javax.swing.JButton jbVolverEstudiante;
    private javax.swing.JPanel jpContenedorEstudiante;
    private javax.swing.JPanel jpContenido;
    private javax.swing.JPanel jpTitulo;
    // End of variables declaration//GEN-END:variables

}
