/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ec.com.donbosquito.vista.moduloPersona;

/**
 *
 * @author Bryam
 */
public class Estudiante extends javax.swing.JInternalFrame {

    /**
     * Creates new form Estudiante
     */
    public Estudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        esudianteprincipalJtbpanel = new javax.swing.JTabbedPane();
        registrarJpanel = new javax.swing.JPanel();
        cedulaRepresentanteTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        correoRepresentanteTxt = new javax.swing.JTextField();
        nombreRepresentanteTxt = new javax.swing.JTextField();
        apellidoRepresentanteTxt = new javax.swing.JTextField();
        direccionRepresentanteTxt = new javax.swing.JTextField();
        telefonoRepresentanteTxt = new javax.swing.JTextField();
        parentescoTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mantenimientoJpanel = new javax.swing.JPanel();
        listarJpanel = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);

        registrarJpanel.setBackground(new java.awt.Color(255, 255, 255));
        registrarJpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cedulaRepresentanteTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        registrarJpanel.add(cedulaRepresentanteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 160, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NOMBRES:");
        registrarJpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ESTUDIANTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        registrarJpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 430, 530));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("APELIDOS:");
        registrarJpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("DIRECCION:");
        registrarJpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("TELEFONO:");
        registrarJpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("CORREO:");
        registrarJpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("CEDULA:");
        registrarJpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jButton2.setText("Guardar");
        registrarJpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 100, -1));

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        registrarJpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 100, -1));

        correoRepresentanteTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        registrarJpanel.add(correoRepresentanteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 160, 30));

        nombreRepresentanteTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        registrarJpanel.add(nombreRepresentanteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 160, 30));

        apellidoRepresentanteTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        registrarJpanel.add(apellidoRepresentanteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 160, 30));

        direccionRepresentanteTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        registrarJpanel.add(direccionRepresentanteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 160, 30));

        telefonoRepresentanteTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        registrarJpanel.add(telefonoRepresentanteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 160, 30));

        parentescoTxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        registrarJpanel.add(parentescoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 160, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("P. FAMILIAR:");
        registrarJpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPRESENTANTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        registrarJpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 430, 480));

        esudianteprincipalJtbpanel.addTab("Registrar", registrarJpanel);

        javax.swing.GroupLayout mantenimientoJpanelLayout = new javax.swing.GroupLayout(mantenimientoJpanel);
        mantenimientoJpanel.setLayout(mantenimientoJpanelLayout);
        mantenimientoJpanelLayout.setHorizontalGroup(
            mantenimientoJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        mantenimientoJpanelLayout.setVerticalGroup(
            mantenimientoJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        esudianteprincipalJtbpanel.addTab("Editar/Eliminar", mantenimientoJpanel);

        javax.swing.GroupLayout listarJpanelLayout = new javax.swing.GroupLayout(listarJpanel);
        listarJpanel.setLayout(listarJpanelLayout);
        listarJpanelLayout.setHorizontalGroup(
            listarJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        listarJpanelLayout.setVerticalGroup(
            listarJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        esudianteprincipalJtbpanel.addTab("Listar", listarJpanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(esudianteprincipalJtbpanel)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(esudianteprincipalJtbpanel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoRepresentanteTxt;
    private javax.swing.JTextField cedulaRepresentanteTxt;
    private javax.swing.JTextField cedulaTxt;
    private javax.swing.JTextField correoRepresentanteTxt;
    private javax.swing.JTextField direccionRepresentanteTxt;
    private javax.swing.JTabbedPane esudianteprincipalJtbpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel listarJpanel;
    private javax.swing.JPanel mantenimientoJpanel;
    private javax.swing.JTextField nombreRepresentanteTxt;
    private javax.swing.JTextField parentescoTxt;
    private javax.swing.JPanel registrarJpanel;
    private javax.swing.JTextField telefonoRepresentanteTxt;
    // End of variables declaration//GEN-END:variables
}
