package edu.ec.com.donbosquito.vista.moduloPersona;

import edu.ec.com.donbosquito.controlador.moduloPersona.ControladorEstudiante;
import edu.ec.com.donbosquito.controlador.moduloPersona.ControladorRepresentante;
import edu.ec.com.donbosquito.modelo.moduloPersona.Docente;
import edu.ec.com.donbosquito.modelo.moduloPersona.Estudiante;
import edu.ec.com.donbosquito.modelo.moduloPersona.Representante;
import edu.ec.com.donbosquito.modelo.moduloPersona.Persona;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fernandosanchez
 */
public class EstudianteCrear extends javax.swing.JPanel {
    
    ControladorRepresentante controladorRepresentante = new ControladorRepresentante();
    ControladorEstudiante controladorEstudiante = new ControladorEstudiante();
    

    /**
     * Creates new form NewJPanel
     */
    public EstudianteCrear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCrearEstudiante = new javax.swing.JPanel();
        jlCedulaRepresentante = new javax.swing.JLabel();
        jlNombreRepresentante = new javax.swing.JLabel();
        txtCedulaBuscarRepresentante = new javax.swing.JTextField();
        txtNombreBuscarRepresentante = new javax.swing.JTextField();
        jLApellidosRepresentante = new javax.swing.JLabel();
        txtApellidosBuscarRepresentante = new javax.swing.JTextField();
        jlDireccionRepresentante = new javax.swing.JLabel();
        txtDireccionBuscarRepresentante = new javax.swing.JTextField();
        jlTelefonoRepresentante = new javax.swing.JLabel();
        txtTelefonoBuscarRepresentante = new javax.swing.JTextField();
        jlCorreoRepresentante = new javax.swing.JLabel();
        txtCorreoBuscarRepresentante = new javax.swing.JTextField();
        jlParentescoRepresentante = new javax.swing.JLabel();
        txtParentescoBuscarRepresentante = new javax.swing.JTextField();
        jbBuscarRepresentante = new javax.swing.JButton();
        jbLimpiarEstudiante = new javax.swing.JButton();
        jlBuscarRepresentante = new javax.swing.JLabel();
        txtBuscarRepresentante = new javax.swing.JTextField();
        jlCedulaEstudiante = new javax.swing.JLabel();
        txtCedulaEstudiante = new javax.swing.JTextField();
        txtNombreEstudiante = new javax.swing.JTextField();
        jlNombreEstudiante = new javax.swing.JLabel();
        txtApellidosEstudiante = new javax.swing.JTextField();
        txtDireccionEstudiante = new javax.swing.JTextField();
        txtTelefonoEstudiante = new javax.swing.JTextField();
        txtCorreoEstudiante = new javax.swing.JTextField();
        jLApellidosEstudiante = new javax.swing.JLabel();
        jlDireccionEstudiante = new javax.swing.JLabel();
        jlTelefonoEstudiante = new javax.swing.JLabel();
        jlCorreoEstudiante = new javax.swing.JLabel();
        jbGuardarEstudiante = new javax.swing.JButton();
        txtFechaNacimientoEstudiante = new javax.swing.JTextField();
        txtEdadEstudiante = new javax.swing.JTextField();
        txtFechaInscripcionEstudiante = new javax.swing.JTextField();
        jlFechaNacimientoEstudiante = new javax.swing.JLabel();
        jlEdadEstududiante = new javax.swing.JLabel();
        jlFechaIncripcionEstudiante = new javax.swing.JLabel();

        jPanelCrearEstudiante.setBackground(new java.awt.Color(51, 51, 51));

        jlCedulaRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jlCedulaRepresentante.setText("Cédula:");

        jlNombreRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jlNombreRepresentante.setText("Nombre:");

        txtCedulaBuscarRepresentante.setBackground(new java.awt.Color(153, 153, 153));

        txtNombreBuscarRepresentante.setBackground(new java.awt.Color(153, 153, 153));

        jLApellidosRepresentante.setBackground(new java.awt.Color(204, 204, 204));
        jLApellidosRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jLApellidosRepresentante.setText("Apellidos:");

        txtApellidosBuscarRepresentante.setBackground(new java.awt.Color(153, 153, 153));

        jlDireccionRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jlDireccionRepresentante.setText("Dirección:");

        txtDireccionBuscarRepresentante.setBackground(new java.awt.Color(153, 153, 153));

        jlTelefonoRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jlTelefonoRepresentante.setText("Teléfono:");

        txtTelefonoBuscarRepresentante.setBackground(new java.awt.Color(153, 153, 153));

        jlCorreoRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jlCorreoRepresentante.setText("Correo:");

        txtCorreoBuscarRepresentante.setBackground(new java.awt.Color(153, 153, 153));

        jlParentescoRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jlParentescoRepresentante.setText("Parentesco Familiar:");

        txtParentescoBuscarRepresentante.setBackground(new java.awt.Color(153, 153, 153));

        jbBuscarRepresentante.setBackground(new java.awt.Color(51, 51, 51));
        jbBuscarRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jbBuscarRepresentante.setText("Buscar");
        jbBuscarRepresentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarRepresentanteActionPerformed(evt);
            }
        });

        jbLimpiarEstudiante.setBackground(new java.awt.Color(51, 51, 51));
        jbLimpiarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jbLimpiarEstudiante.setText("Limpiar");
        jbLimpiarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarEstudianteActionPerformed(evt);
            }
        });

        jlBuscarRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jlBuscarRepresentante.setText("Ingresar Cédula:");

        txtBuscarRepresentante.setBackground(new java.awt.Color(153, 153, 153));

        jlCedulaEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlCedulaEstudiante.setText("Cédula:");

        txtCedulaEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        txtNombreEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        jlNombreEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlNombreEstudiante.setText("Nombre:");

        txtApellidosEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        txtDireccionEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        txtTelefonoEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        txtCorreoEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        jLApellidosEstudiante.setBackground(new java.awt.Color(204, 204, 204));
        jLApellidosEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jLApellidosEstudiante.setText("Apellidos:");

        jlDireccionEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlDireccionEstudiante.setText("Dirección:");

        jlTelefonoEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlTelefonoEstudiante.setText("Teléfono:");

        jlCorreoEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlCorreoEstudiante.setText("Correo:");

        jbGuardarEstudiante.setBackground(new java.awt.Color(51, 51, 51));
        jbGuardarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jbGuardarEstudiante.setText("Guardar");
        jbGuardarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarEstudianteActionPerformed(evt);
            }
        });

        txtFechaNacimientoEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        txtEdadEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        txtFechaInscripcionEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        jlFechaNacimientoEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlFechaNacimientoEstudiante.setText("Fecha Nacimiento:");

        jlEdadEstududiante.setForeground(new java.awt.Color(204, 204, 204));
        jlEdadEstududiante.setText("Edad:");

        jlFechaIncripcionEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlFechaIncripcionEstudiante.setText("Fecha Inscripción:");

        javax.swing.GroupLayout jPanelCrearEstudianteLayout = new javax.swing.GroupLayout(jPanelCrearEstudiante);
        jPanelCrearEstudiante.setLayout(jPanelCrearEstudianteLayout);
        jPanelCrearEstudianteLayout.setHorizontalGroup(
            jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearEstudianteLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jbGuardarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLimpiarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearEstudianteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCrearEstudianteLayout.createSequentialGroup()
                        .addComponent(jlFechaIncripcionEstudiante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFechaInscripcionEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCrearEstudianteLayout.createSequentialGroup()
                        .addComponent(jLApellidosEstudiante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtApellidosEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCrearEstudianteLayout.createSequentialGroup()
                        .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCedulaEstudiante)
                            .addComponent(jlNombreEstudiante)
                            .addComponent(jlTelefonoEstudiante)
                            .addComponent(jlCorreoEstudiante)
                            .addComponent(jlFechaNacimientoEstudiante)
                            .addComponent(jlEdadEstududiante))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdadEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaNacimientoEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefonoEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedulaEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreoEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCrearEstudianteLayout.createSequentialGroup()
                        .addComponent(jlDireccionEstudiante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDireccionEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearEstudianteLayout.createSequentialGroup()
                        .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTelefonoRepresentante)
                            .addComponent(jlCorreoRepresentante)
                            .addComponent(jlDireccionRepresentante)
                            .addComponent(jLApellidosRepresentante)
                            .addComponent(jlNombreRepresentante)
                            .addComponent(jlCedulaRepresentante)
                            .addComponent(jlBuscarRepresentante))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearEstudianteLayout.createSequentialGroup()
                        .addComponent(jlParentescoRepresentante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtNombreBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCedulaBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtApellidosBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDireccionBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelefonoBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCorreoBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtParentescoBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanelCrearEstudianteLayout.setVerticalGroup(
            jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearEstudianteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCrearEstudianteLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlBuscarRepresentante, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(txtCedulaEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCedulaEstudiante))))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscarRepresentante)
                    .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNombreEstudiante))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCedulaRepresentante)
                    .addComponent(txtCedulaBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidosEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLApellidosEstudiante))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCrearEstudianteLayout.createSequentialGroup()
                        .addComponent(jlDireccionEstudiante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelCrearEstudianteLayout.createSequentialGroup()
                            .addComponent(jlNombreRepresentante)
                            .addGap(22, 22, 22))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearEstudianteLayout.createSequentialGroup()
                            .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtDireccionEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18))))
                .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellidosRepresentante)
                    .addComponent(txtApellidosBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTelefonoEstudiante))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDireccionRepresentante)
                    .addComponent(txtCorreoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCorreoEstudiante))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefonoRepresentante)
                    .addComponent(txtTelefonoBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaNacimientoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFechaNacimientoEstudiante))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCorreoRepresentante)
                    .addComponent(txtCorreoBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdadEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEdadEstududiante))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlParentescoRepresentante)
                    .addComponent(txtParentescoBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaInscripcionEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFechaIncripcionEstudiante))
                .addGap(31, 31, 31)
                .addGroup(jPanelCrearEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpiarEstudiante)
                    .addComponent(jbGuardarEstudiante))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelCrearEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelCrearEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimpiarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarEstudianteActionPerformed
        // TODO add your handling code here:
        limpiar();
        
    }//GEN-LAST:event_jbLimpiarEstudianteActionPerformed

    private void jbBuscarRepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarRepresentanteActionPerformed
        // TODO add your handling code here:
        buscarRepresentante();
        
    }//GEN-LAST:event_jbBuscarRepresentanteActionPerformed

    private void jbGuardarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarEstudianteActionPerformed
        // TODO add your handling code here:
        crearEstudiante();
        
    }//GEN-LAST:event_jbGuardarEstudianteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLApellidosEstudiante;
    private javax.swing.JLabel jLApellidosRepresentante;
    private javax.swing.JPanel jPanelCrearEstudiante;
    private javax.swing.JButton jbBuscarRepresentante;
    private javax.swing.JButton jbGuardarEstudiante;
    private javax.swing.JButton jbLimpiarEstudiante;
    private javax.swing.JLabel jlBuscarRepresentante;
    private javax.swing.JLabel jlCedulaEstudiante;
    private javax.swing.JLabel jlCedulaRepresentante;
    private javax.swing.JLabel jlCorreoEstudiante;
    private javax.swing.JLabel jlCorreoRepresentante;
    private javax.swing.JLabel jlDireccionEstudiante;
    private javax.swing.JLabel jlDireccionRepresentante;
    private javax.swing.JLabel jlEdadEstududiante;
    private javax.swing.JLabel jlFechaIncripcionEstudiante;
    private javax.swing.JLabel jlFechaNacimientoEstudiante;
    private javax.swing.JLabel jlNombreEstudiante;
    private javax.swing.JLabel jlNombreRepresentante;
    private javax.swing.JLabel jlParentescoRepresentante;
    private javax.swing.JLabel jlTelefonoEstudiante;
    private javax.swing.JLabel jlTelefonoRepresentante;
    private javax.swing.JTextField txtApellidosBuscarRepresentante;
    private javax.swing.JTextField txtApellidosEstudiante;
    private javax.swing.JTextField txtBuscarRepresentante;
    private javax.swing.JTextField txtCedulaBuscarRepresentante;
    private javax.swing.JTextField txtCedulaEstudiante;
    private javax.swing.JTextField txtCorreoBuscarRepresentante;
    private javax.swing.JTextField txtCorreoEstudiante;
    private javax.swing.JTextField txtDireccionBuscarRepresentante;
    private javax.swing.JTextField txtDireccionEstudiante;
    private javax.swing.JTextField txtEdadEstudiante;
    private javax.swing.JTextField txtFechaInscripcionEstudiante;
    private javax.swing.JTextField txtFechaNacimientoEstudiante;
    private javax.swing.JTextField txtNombreBuscarRepresentante;
    private javax.swing.JTextField txtNombreEstudiante;
    private javax.swing.JTextField txtParentescoBuscarRepresentante;
    private javax.swing.JTextField txtTelefonoBuscarRepresentante;
    private javax.swing.JTextField txtTelefonoEstudiante;
    // End of variables declaration//GEN-END:variables
    void buscarRepresentante(){
        Persona persona = new Persona(0, "", "", "", "", "", "") {
        };
        Representante representante = new Representante(0, "", persona, 0, "", "", "", "", "", "");
        representante = controladorRepresentante.buscarCedulaRepresentante(txtBuscarRepresentante.getText());
        txtCedulaBuscarRepresentante.setText(representante.getCedula());
        txtNombreBuscarRepresentante.setText(representante.getNombre());
        txtApellidosBuscarRepresentante.setText(representante.getApellido());
        txtDireccionBuscarRepresentante.setText(representante.getDireccion());
        txtTelefonoBuscarRepresentante.setText(representante.getTelefono());
        txtCorreoBuscarRepresentante.setText(representante.getCorreo());
        txtParentescoBuscarRepresentante.setText(representante.getParentescoFamiliar());
        txtBuscarRepresentante.setText("");   
    }
    
    void crearEstudiante(){
        Persona persona = new Persona(0, "", "", "", "", "", "") {
        };
        Docente docente = new Docente(0, "", persona, 0, "", "", "", "", "", "");
        Representante representante = new Representante(0, "", persona, 0, "", "", "", "", "", "");
        Estudiante estudiante = new Estudiante(0, ParseFecha("0/0/0"), 0, ParseFecha("0/0/0"), persona, representante, 0, "", "", "", "", "", "");
        ControladorEstudiante controladorEstudiante = new ControladorEstudiante();
        ControladorRepresentante controladorRepresentante = new ControladorRepresentante();
        estudiante.setCodigoPersona(controladorEstudiante.buscarCodigo());
        estudiante.setCedula(txtCedulaEstudiante.getText());
        estudiante.setNombre(txtNombreEstudiante.getText());
        estudiante.setApellido(txtApellidosEstudiante.getText());
        estudiante.setDireccion(txtDireccionEstudiante.getText());
        estudiante.setTelefono(txtTelefonoEstudiante.getText());
        estudiante.setCorreo(txtCorreoEstudiante.getText());
        estudiante.setFechaNaciemiento(ParseFecha(txtFechaNacimientoEstudiante.getText()));
        estudiante.setEdad(Integer.valueOf(txtEdadEstudiante.getText()));
        estudiante.setFechaInscripcion(ParseFecha(txtFechaInscripcionEstudiante.getText()));
        estudiante.setPersona(estudiante);
        estudiante.setRepresentante((Representante) controladorRepresentante.buscarCedulaRepresentante(txtCedulaBuscarRepresentante.getText()));       
        controladorEstudiante.crearUsuario(estudiante, docente, representante, persona);
        limpiar();
        
    }
    
    void limpiar(){
        txtBuscarRepresentante.setText("");      
        txtCedulaBuscarRepresentante.setText("");
        txtCedulaEstudiante.setText("");
        txtNombreBuscarRepresentante.setText("");
        txtNombreEstudiante.setText("");
        txtApellidosBuscarRepresentante.setText("");
        txtApellidosEstudiante.setText("");
        txtDireccionBuscarRepresentante.setText("");
        txtDireccionEstudiante.setText("");
        txtTelefonoBuscarRepresentante.setText("");
        txtTelefonoEstudiante.setText("");
        txtCorreoBuscarRepresentante.setText("");
        txtCorreoEstudiante.setText("");
        txtParentescoBuscarRepresentante.setText("");
        txtFechaInscripcionEstudiante.setText("");
        txtFechaNacimientoEstudiante.setText("");
        txtEdadEstudiante.setText("");
        
        
    }
    
    public static Date ParseFecha(String fecha) {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate = null;
        try {
            fechaDate = formato.parse(fecha);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        return fechaDate;
    }
}
