package edu.ec.com.donbosquito.vista.moduloPersona;

import edu.ec.com.donbosquito.controlador.moduloPersona.ControladorEstudiante;
import edu.ec.com.donbosquito.controlador.moduloPersona.ControladorRepresentante;
import edu.ec.com.donbosquito.modelo.moduloPersona.Docente;
import edu.ec.com.donbosquito.modelo.moduloPersona.Estudiante;
import edu.ec.com.donbosquito.modelo.moduloPersona.Persona;
import edu.ec.com.donbosquito.modelo.moduloPersona.Representante;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author fernandosanchez
 */
public class EstudianteEliminar extends javax.swing.JPanel {

    ControladorEstudiante controladorEstudiante = new ControladorEstudiante();
    ControladorRepresentante controladorRepresentante = new ControladorRepresentante();
    String aux;

    /**
     * Creates new form NewJPanel
     */
    public EstudianteEliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBuscarEstudiante = new javax.swing.JPanel();
        jlCedulaEliminarEstudiante = new javax.swing.JLabel();
        jlNombreEliminarEstudiante = new javax.swing.JLabel();
        txtCedulaEliminarEstudiante = new javax.swing.JTextField();
        txtNombreEliminarEstudiante = new javax.swing.JTextField();
        jLApellidosEliminarEstudiante = new javax.swing.JLabel();
        txtApellidosEliminarEstudiante = new javax.swing.JTextField();
        jlDireccionEliminarEstudiante = new javax.swing.JLabel();
        txtDireccionEliminarEstudiante = new javax.swing.JTextField();
        jlTelefonoEliminarEstudiante = new javax.swing.JLabel();
        txtTelefonoEliminarEstudiante = new javax.swing.JTextField();
        jlCorreoEliminarEstudiante = new javax.swing.JLabel();
        txtCorreoEliminarEstudiante = new javax.swing.JTextField();
        jlFechaNacimientoEliminarEstudiante = new javax.swing.JLabel();
        txtFechaNacimientoEliminarEstudiante = new javax.swing.JTextField();
        jbBuscarEliminarEstudiante = new javax.swing.JButton();
        jbLimpiarEliminarEstudiante = new javax.swing.JButton();
        jlBuscarEliminarCedula = new javax.swing.JLabel();
        txtBuscarCedulaEliminarEstudiante = new javax.swing.JTextField();
        txtEdadEliminarEstudiante = new javax.swing.JTextField();
        jlEdadEliminarEstudiante = new javax.swing.JLabel();
        txtFechaInscripcionEliminarEstudiante = new javax.swing.JTextField();
        jlFechaIncripcionEliminarEstudiante = new javax.swing.JLabel();
        jlRepresentanteEliminar = new javax.swing.JLabel();
        jlCedulaEliminarRepresentante = new javax.swing.JLabel();
        txtCedulaEliminarRepresentante = new javax.swing.JTextField();
        jlNombreEliminarRepresentante = new javax.swing.JLabel();
        txtNombreEliminarRepresentante = new javax.swing.JTextField();
        jLApellidosEliminarRepresentante = new javax.swing.JLabel();
        txtApellidosEliminarRepresentante = new javax.swing.JTextField();
        jlDireccionEliminarRepresentante = new javax.swing.JLabel();
        txtDireccionEliminarRepresentante = new javax.swing.JTextField();
        jlTelefonoEliminarRepresentante = new javax.swing.JLabel();
        txtTelefonoEliminarRepresentante = new javax.swing.JTextField();
        jlCorreoEliminarRepresentante = new javax.swing.JLabel();
        txtCorreoEliminarRepresentante = new javax.swing.JTextField();
        jlParentescoFamiliarEliminarRepresentante = new javax.swing.JLabel();
        txtParentescoFamiliarEliminarRepresentante = new javax.swing.JTextField();
        jbEliminarEstudiante = new javax.swing.JButton();

        jPanelBuscarEstudiante.setBackground(new java.awt.Color(51, 51, 51));

        jlCedulaEliminarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlCedulaEliminarEstudiante.setText("Cédula:");

        jlNombreEliminarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlNombreEliminarEstudiante.setText("Nombre:");

        txtCedulaEliminarEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        txtNombreEliminarEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        jLApellidosEliminarEstudiante.setBackground(new java.awt.Color(204, 204, 204));
        jLApellidosEliminarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jLApellidosEliminarEstudiante.setText("Apellidos:");

        txtApellidosEliminarEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        jlDireccionEliminarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlDireccionEliminarEstudiante.setText("Dirección:");

        txtDireccionEliminarEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        jlTelefonoEliminarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlTelefonoEliminarEstudiante.setText("Teléfono:");

        txtTelefonoEliminarEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        jlCorreoEliminarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlCorreoEliminarEstudiante.setText("Correo:");

        txtCorreoEliminarEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        jlFechaNacimientoEliminarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlFechaNacimientoEliminarEstudiante.setText("Fecha Nacimiento:");

        txtFechaNacimientoEliminarEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        jbBuscarEliminarEstudiante.setBackground(new java.awt.Color(51, 51, 51));
        jbBuscarEliminarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jbBuscarEliminarEstudiante.setText("Buscar");
        jbBuscarEliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarEliminarEstudianteActionPerformed(evt);
            }
        });

        jbLimpiarEliminarEstudiante.setBackground(new java.awt.Color(51, 51, 51));
        jbLimpiarEliminarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jbLimpiarEliminarEstudiante.setText("Limpiar");
        jbLimpiarEliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarEliminarEstudianteActionPerformed(evt);
            }
        });

        jlBuscarEliminarCedula.setForeground(new java.awt.Color(204, 204, 204));
        jlBuscarEliminarCedula.setText("Ingresar Cédula Estudiante:");

        txtBuscarCedulaEliminarEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        txtEdadEliminarEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        jlEdadEliminarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlEdadEliminarEstudiante.setText("Edad:");

        txtFechaInscripcionEliminarEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        jlFechaIncripcionEliminarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlFechaIncripcionEliminarEstudiante.setText("Fecha Inscripción:");

        jlRepresentanteEliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlRepresentanteEliminar.setForeground(new java.awt.Color(204, 204, 204));
        jlRepresentanteEliminar.setText("Representante:");

        jlCedulaEliminarRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jlCedulaEliminarRepresentante.setText("Cédula:");

        txtCedulaEliminarRepresentante.setBackground(new java.awt.Color(153, 153, 153));

        jlNombreEliminarRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jlNombreEliminarRepresentante.setText("Nombre:");

        txtNombreEliminarRepresentante.setBackground(new java.awt.Color(153, 153, 153));

        jLApellidosEliminarRepresentante.setBackground(new java.awt.Color(204, 204, 204));
        jLApellidosEliminarRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jLApellidosEliminarRepresentante.setText("Apellidos:");

        txtApellidosEliminarRepresentante.setBackground(new java.awt.Color(153, 153, 153));

        jlDireccionEliminarRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jlDireccionEliminarRepresentante.setText("Dirección:");

        txtDireccionEliminarRepresentante.setBackground(new java.awt.Color(153, 153, 153));

        jlTelefonoEliminarRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jlTelefonoEliminarRepresentante.setText("Teléfono:");

        txtTelefonoEliminarRepresentante.setBackground(new java.awt.Color(153, 153, 153));

        jlCorreoEliminarRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jlCorreoEliminarRepresentante.setText("Correo:");

        txtCorreoEliminarRepresentante.setBackground(new java.awt.Color(153, 153, 153));

        jlParentescoFamiliarEliminarRepresentante.setForeground(new java.awt.Color(204, 204, 204));
        jlParentescoFamiliarEliminarRepresentante.setText("Parentesco Familiar:");

        txtParentescoFamiliarEliminarRepresentante.setBackground(new java.awt.Color(153, 153, 153));

        jbEliminarEstudiante.setBackground(new java.awt.Color(51, 51, 51));
        jbEliminarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jbEliminarEstudiante.setText("Eliminar");
        jbEliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarEstudianteLayout = new javax.swing.GroupLayout(jPanelBuscarEstudiante);
        jPanelBuscarEstudiante.setLayout(jPanelBuscarEstudianteLayout);
        jPanelBuscarEstudianteLayout.setHorizontalGroup(
            jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarEstudianteLayout.createSequentialGroup()
                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarEstudianteLayout.createSequentialGroup()
                        .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBuscarEstudianteLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlCedulaEliminarEstudiante)
                                    .addComponent(jlNombreEliminarEstudiante)
                                    .addComponent(jLApellidosEliminarEstudiante)
                                    .addComponent(jlDireccionEliminarEstudiante)
                                    .addComponent(jlTelefonoEliminarEstudiante)
                                    .addComponent(jlCorreoEliminarEstudiante)
                                    .addComponent(jlFechaNacimientoEliminarEstudiante)
                                    .addComponent(jlEdadEliminarEstudiante)
                                    .addComponent(jlFechaIncripcionEliminarEstudiante))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreEliminarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(txtApellidosEliminarEstudiante)
                                    .addComponent(txtDireccionEliminarEstudiante)
                                    .addComponent(txtTelefonoEliminarEstudiante)
                                    .addComponent(txtCorreoEliminarEstudiante)
                                    .addComponent(txtFechaNacimientoEliminarEstudiante)
                                    .addComponent(txtEdadEliminarEstudiante)
                                    .addComponent(txtFechaInscripcionEliminarEstudiante)
                                    .addComponent(txtCedulaEliminarEstudiante)))
                            .addGroup(jPanelBuscarEstudianteLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(txtBuscarCedulaEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jbBuscarEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBuscarEstudianteLayout.createSequentialGroup()
                                .addComponent(jlNombreEliminarRepresentante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombreEliminarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBuscarEstudianteLayout.createSequentialGroup()
                                .addComponent(jLApellidosEliminarRepresentante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtApellidosEliminarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBuscarEstudianteLayout.createSequentialGroup()
                                .addComponent(jlDireccionEliminarRepresentante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(txtDireccionEliminarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBuscarEstudianteLayout.createSequentialGroup()
                                .addComponent(jlTelefonoEliminarRepresentante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTelefonoEliminarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBuscarEstudianteLayout.createSequentialGroup()
                                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlCorreoEliminarRepresentante)
                                    .addComponent(jlParentescoFamiliarEliminarRepresentante))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtParentescoFamiliarEliminarRepresentante, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(txtCorreoEliminarRepresentante)))
                            .addGroup(jPanelBuscarEstudianteLayout.createSequentialGroup()
                                .addComponent(jlCedulaEliminarRepresentante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlRepresentanteEliminar)
                                    .addComponent(txtCedulaEliminarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelBuscarEstudianteLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jbEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbLimpiarEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
            .addGroup(jPanelBuscarEstudianteLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jlBuscarEliminarCedula)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBuscarEstudianteLayout.setVerticalGroup(
            jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlBuscarEliminarCedula)
                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarEstudianteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jlRepresentanteEliminar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarEstudianteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarCedulaEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscarEliminarEstudiante))))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCedulaEliminarEstudiante)
                    .addComponent(txtCedulaEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCedulaEliminarRepresentante)
                    .addComponent(txtCedulaEliminarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNombreEliminarEstudiante)
                    .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombreEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlNombreEliminarRepresentante)
                        .addComponent(txtNombreEliminarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLApellidosEliminarEstudiante)
                    .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtApellidosEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLApellidosEliminarRepresentante)
                        .addComponent(txtApellidosEliminarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDireccionEliminarEstudiante)
                    .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDireccionEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlDireccionEliminarRepresentante)
                        .addComponent(txtDireccionEliminarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTelefonoEliminarEstudiante)
                    .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTelefonoEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlTelefonoEliminarRepresentante)
                        .addComponent(txtTelefonoEliminarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCorreoEliminarEstudiante)
                    .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCorreoEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlCorreoEliminarRepresentante)
                        .addComponent(txtCorreoEliminarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlFechaNacimientoEliminarEstudiante)
                    .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFechaNacimientoEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlParentescoFamiliarEliminarRepresentante)
                        .addComponent(txtParentescoFamiliarEliminarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdadEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEdadEliminarEstudiante))
                .addGap(18, 18, 18)
                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaInscripcionEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFechaIncripcionEliminarEstudiante))
                .addGap(15, 15, 15)
                .addGroup(jPanelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpiarEliminarEstudiante)
                    .addComponent(jbEliminarEstudiante))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBuscarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimpiarEliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarEliminarEstudianteActionPerformed
        // TODO add your handling code here:
        limpiar();

    }//GEN-LAST:event_jbLimpiarEliminarEstudianteActionPerformed

    private void jbBuscarEliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarEliminarEstudianteActionPerformed
        // TODO add your handling code here:

        buscarEstudiante();

    }//GEN-LAST:event_jbBuscarEliminarEstudianteActionPerformed

    private void jbEliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarEstudianteActionPerformed
        // TODO add your handling code here:
        eliminarEstudiante();
    }//GEN-LAST:event_jbEliminarEstudianteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLApellidosEliminarEstudiante;
    private javax.swing.JLabel jLApellidosEliminarRepresentante;
    private javax.swing.JPanel jPanelBuscarEstudiante;
    private javax.swing.JButton jbBuscarEliminarEstudiante;
    private javax.swing.JButton jbEliminarEstudiante;
    private javax.swing.JButton jbLimpiarEliminarEstudiante;
    private javax.swing.JLabel jlBuscarEliminarCedula;
    private javax.swing.JLabel jlCedulaEliminarEstudiante;
    private javax.swing.JLabel jlCedulaEliminarRepresentante;
    private javax.swing.JLabel jlCorreoEliminarEstudiante;
    private javax.swing.JLabel jlCorreoEliminarRepresentante;
    private javax.swing.JLabel jlDireccionEliminarEstudiante;
    private javax.swing.JLabel jlDireccionEliminarRepresentante;
    private javax.swing.JLabel jlEdadEliminarEstudiante;
    private javax.swing.JLabel jlFechaIncripcionEliminarEstudiante;
    private javax.swing.JLabel jlFechaNacimientoEliminarEstudiante;
    private javax.swing.JLabel jlNombreEliminarEstudiante;
    private javax.swing.JLabel jlNombreEliminarRepresentante;
    private javax.swing.JLabel jlParentescoFamiliarEliminarRepresentante;
    private javax.swing.JLabel jlRepresentanteEliminar;
    private javax.swing.JLabel jlTelefonoEliminarEstudiante;
    private javax.swing.JLabel jlTelefonoEliminarRepresentante;
    private javax.swing.JTextField txtApellidosEliminarEstudiante;
    private javax.swing.JTextField txtApellidosEliminarRepresentante;
    private javax.swing.JTextField txtBuscarCedulaEliminarEstudiante;
    private javax.swing.JTextField txtCedulaEliminarEstudiante;
    private javax.swing.JTextField txtCedulaEliminarRepresentante;
    private javax.swing.JTextField txtCorreoEliminarEstudiante;
    private javax.swing.JTextField txtCorreoEliminarRepresentante;
    private javax.swing.JTextField txtDireccionEliminarEstudiante;
    private javax.swing.JTextField txtDireccionEliminarRepresentante;
    private javax.swing.JTextField txtEdadEliminarEstudiante;
    private javax.swing.JTextField txtFechaInscripcionEliminarEstudiante;
    private javax.swing.JTextField txtFechaNacimientoEliminarEstudiante;
    private javax.swing.JTextField txtNombreEliminarEstudiante;
    private javax.swing.JTextField txtNombreEliminarRepresentante;
    private javax.swing.JTextField txtParentescoFamiliarEliminarRepresentante;
    private javax.swing.JTextField txtTelefonoEliminarEstudiante;
    private javax.swing.JTextField txtTelefonoEliminarRepresentante;
    // End of variables declaration//GEN-END:variables
    void buscarEstudiante() {
        Persona persona = new Persona(0, "", "", "", "", "", "") {
        };
        Docente docente = new Docente(0, "", persona, 0, "", "", "", "", "", "");

        Representante representante = new Representante(0, "", persona, 0, "", "", "", "", "", "");
        Estudiante estudiante = new Estudiante(0, ParseFecha("0/0/0"), 0, ParseFecha("0/0/0"), persona, representante, 0, "", "", "", "", "", "");

        estudiante = controladorEstudiante.buscarCedulaEstudiante(txtBuscarCedulaEliminarEstudiante.getText());
        txtCedulaEliminarEstudiante.setText(estudiante.getCedula());
        txtNombreEliminarEstudiante.setText(estudiante.getNombre());
        txtApellidosEliminarEstudiante.setText(estudiante.getApellido());
        txtDireccionEliminarEstudiante.setText(estudiante.getDireccion());
        txtTelefonoEliminarEstudiante.setText(estudiante.getTelefono());
        txtCorreoEliminarEstudiante.setText(estudiante.getCorreo());
        txtFechaNacimientoEliminarEstudiante.setText(fecha(String.valueOf(estudiante.getFechaNaciemiento())));
        txtEdadEliminarEstudiante.setText(String.valueOf(estudiante.getEdad()));
        txtFechaInscripcionEliminarEstudiante.setText(fecha(String.valueOf(estudiante.getFechaInscripcion())));
        representante = controladorRepresentante.buscarUsuario(estudiante.getRepresentante().getCodigoPersona());
        txtCedulaEliminarRepresentante.setText(representante.getCedula());
        txtNombreEliminarRepresentante.setText(representante.getNombre());
        txtApellidosEliminarRepresentante.setText(representante.getApellido());
        txtDireccionEliminarRepresentante.setText(representante.getDireccion());
        txtTelefonoEliminarRepresentante.setText(representante.getTelefono());
        txtCorreoEliminarRepresentante.setText(representante.getCorreo());
        txtParentescoFamiliarEliminarRepresentante.setText(representante.getParentescoFamiliar());
        aux = txtBuscarCedulaEliminarEstudiante.getText();

        txtBuscarCedulaEliminarEstudiante.setText("");
    }

    void eliminarEstudiante() {
        Persona persona = new Persona(0, "", "", "", "", "", "") {
        };
        Docente docente = new Docente(0, "", persona, 0, "", "", "", "", "", "");
        Representante representante = new Representante(0, "", persona, 0, "", "", "", "", "", "");
        Estudiante estudiante = new Estudiante(0, ParseFecha("0/0/0"), 0, ParseFecha("0/0/0"), persona, representante, 0, "", "", "", "", "", "");
        estudiante = controladorEstudiante.buscarCedulaEstudiante(txtCedulaEliminarEstudiante.getText());        
        estudiante.setCodigoPersona(estudiante.getCodigoPersona());
        controladorEstudiante.eliminarUsuario(estudiante, docente, representante, persona);
        
        limpiar();
    }

    void limpiar() {
        txtBuscarCedulaEliminarEstudiante.setText("");
        txtCedulaEliminarEstudiante.setText("");
        txtCedulaEliminarRepresentante.setText("");
        txtNombreEliminarEstudiante.setText("");
        txtNombreEliminarRepresentante.setText("");
        txtApellidosEliminarEstudiante.setText("");
        txtApellidosEliminarRepresentante.setText("");
        txtDireccionEliminarEstudiante.setText("");
        txtDireccionEliminarRepresentante.setText("");
        txtTelefonoEliminarEstudiante.setText("");
        txtTelefonoEliminarRepresentante.setText("");
        txtCorreoEliminarEstudiante.setText("");
        txtCorreoEliminarRepresentante.setText("");
        txtFechaNacimientoEliminarEstudiante.setText("");
        txtEdadEliminarEstudiante.setText("");
        txtParentescoFamiliarEliminarRepresentante.setText("");
        txtFechaInscripcionEliminarEstudiante.setText("");
    }

    String fecha(String fecha) {
    
        String[] parts = fecha.split("-");
        String part1 = parts[0]; 
        String part2 = parts[1];
        String part3 = parts[2]; 
        fecha = part3+"/"+part2+"/"+part1;
        return fecha;
    }

    public static Date ParseFecha(String fecha) {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate = null;
        try {
            fechaDate = formato.parse(fecha);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        return fechaDate;
    }
}
