/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ec.com.donbosquito.vista.principal;

import edu.ec.com.donbosquito.controlador.moduloPersona.ControladorDocente;
import edu.ec.com.donbosquito.controlador.moduloPersona.ControladorEstudiante;
import edu.ec.com.donbosquito.controlador.moduloPersona.ControladorRepresentante;
import edu.ec.com.donbosquito.vista.moduloPersona.DocenteVista;
import edu.ec.com.donbosquito.vista.moduloPersona.EstudianteVista;
import edu.ec.com.donbosquito.vista.moduloPersona.MenuRepresentante;

/**
 *
 * @author Bryam
 */
public class Escritorio extends javax.swing.JFrame {

    private MenuRepresentante menuRepresentante;
    private EstudianteVista estudianteVista;
    private DocenteVista docenteVista;
    
    private ControladorRepresentante controladorRepresentante;
    private ControladorDocente controladorDocente;
    private ControladorEstudiante controladorEstudiante;
    
  
    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        controladorDocente = new ControladorDocente();
        controladorEstudiante = new  ControladorEstudiante();
        controladorRepresentante = new ControladorRepresentante();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorioJdp = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        personaJmbar = new javax.swing.JMenu();
        representanteJmitem = new javax.swing.JMenuItem();
        estudianteJmitem = new javax.swing.JMenuItem();
        docenteJmenuitem = new javax.swing.JMenuItem();
        institucionJmenubar = new javax.swing.JMenu();
        anioJmenuitem = new javax.swing.JMenuItem();
        mencionanioJmenuitem = new javax.swing.JMenuItem();
        materiaanioJmenuitem = new javax.swing.JMenuItem();
        aulaanioJmenuitem = new javax.swing.JMenuItem();
        cursoanioJmenuitem = new javax.swing.JMenuItem();
        matriculaJmenubar = new javax.swing.JMenu();
        matriculaJmenuitem = new javax.swing.JMenuItem();
        facturaJmenubar = new javax.swing.JMenu();
        facturasJmenuitem = new javax.swing.JMenuItem();
        libroJmenuitem = new javax.swing.JMenuItem();
        pagosJmenuitem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        gruposanioJmenuitem = new javax.swing.JMenuItem();
        recordJmenubar = new javax.swing.JMenu();
        calificacionesJmenuItem = new javax.swing.JMenuItem();
        certificadosJmenuitem = new javax.swing.JMenuItem();
        salirJmenubar = new javax.swing.JMenu();
        salirJmenuitem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personaJmbar.setText("Registro Persona");

        representanteJmitem.setText("Representante");
        representanteJmitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                representanteJmitemActionPerformed(evt);
            }
        });
        personaJmbar.add(representanteJmitem);

        estudianteJmitem.setText("Estudiante");
        personaJmbar.add(estudianteJmitem);

        docenteJmenuitem.setText("Docente");
        personaJmbar.add(docenteJmenuitem);

        jMenuBar1.add(personaJmbar);

        institucionJmenubar.setText("Institucion");

        anioJmenuitem.setText("Año Lectivo");
        institucionJmenubar.add(anioJmenuitem);

        mencionanioJmenuitem.setText("Mencion");
        mencionanioJmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencionanioJmenuitemActionPerformed(evt);
            }
        });
        institucionJmenubar.add(mencionanioJmenuitem);

        materiaanioJmenuitem.setText("Materia");
        institucionJmenubar.add(materiaanioJmenuitem);

        aulaanioJmenuitem.setText("Aula");
        institucionJmenubar.add(aulaanioJmenuitem);

        cursoanioJmenuitem.setText("Curso");
        institucionJmenubar.add(cursoanioJmenuitem);

        jMenuBar1.add(institucionJmenubar);

        matriculaJmenubar.setText("Matricula");

        matriculaJmenuitem.setText("Matricula");
        matriculaJmenubar.add(matriculaJmenuitem);

        jMenuBar1.add(matriculaJmenubar);

        facturaJmenubar.setText("Facturacion");

        facturasJmenuitem.setText("Facturas");
        facturaJmenubar.add(facturasJmenuitem);

        libroJmenuitem.setText("Libro Diario");
        libroJmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libroJmenuitemActionPerformed(evt);
            }
        });
        facturaJmenubar.add(libroJmenuitem);

        pagosJmenuitem.setText("Pagos");
        facturaJmenubar.add(pagosJmenuitem);

        jMenuBar1.add(facturaJmenubar);

        jMenu1.setText("Registro Grupos");

        gruposanioJmenuitem.setText("Grupos");
        jMenu1.add(gruposanioJmenuitem);

        jMenuBar1.add(jMenu1);

        recordJmenubar.setText("Record Academico");

        calificacionesJmenuItem.setText("Calificaciones");
        recordJmenubar.add(calificacionesJmenuItem);

        certificadosJmenuitem.setText("Certificados");
        recordJmenubar.add(certificadosJmenuitem);

        jMenuBar1.add(recordJmenubar);

        salirJmenubar.setText("SALIR");

        salirJmenuitem.setText("SALIR");
        salirJmenubar.add(salirJmenuitem);

        jMenuBar1.add(salirJmenubar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(escritorioJdp, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(escritorioJdp, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void representanteJmitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_representanteJmitemActionPerformed
        // TODO add your handling code here:
        if (menuRepresentante != null) {
            menuRepresentante.dispose();
            menuRepresentante = new MenuRepresentante(controladorRepresentante);
            escritorioJdp.add(menuRepresentante);
            menuRepresentante.setVisible(true);
        } else {
            menuRepresentante = new MenuRepresentante(controladorRepresentante);
            escritorioJdp.add(menuRepresentante);
            menuRepresentante.setVisible(true);
        }
        
    }//GEN-LAST:event_representanteJmitemActionPerformed

    private void libroJmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libroJmenuitemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_libroJmenuitemActionPerformed

    private void mencionanioJmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencionanioJmenuitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mencionanioJmenuitemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem anioJmenuitem;
    private javax.swing.JMenuItem aulaanioJmenuitem;
    private javax.swing.JMenuItem calificacionesJmenuItem;
    private javax.swing.JMenuItem certificadosJmenuitem;
    private javax.swing.JMenuItem cursoanioJmenuitem;
    private javax.swing.JMenuItem docenteJmenuitem;
    public static javax.swing.JDesktopPane escritorioJdp;
    private javax.swing.JMenuItem estudianteJmitem;
    private javax.swing.JMenu facturaJmenubar;
    private javax.swing.JMenuItem facturasJmenuitem;
    private javax.swing.JMenuItem gruposanioJmenuitem;
    private javax.swing.JMenu institucionJmenubar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem libroJmenuitem;
    private javax.swing.JMenuItem materiaanioJmenuitem;
    private javax.swing.JMenu matriculaJmenubar;
    private javax.swing.JMenuItem matriculaJmenuitem;
    private javax.swing.JMenuItem mencionanioJmenuitem;
    private javax.swing.JMenuItem pagosJmenuitem;
    private javax.swing.JMenu personaJmbar;
    private javax.swing.JMenu recordJmenubar;
    private javax.swing.JMenuItem representanteJmitem;
    private javax.swing.JMenu salirJmenubar;
    private javax.swing.JMenuItem salirJmenuitem;
    // End of variables declaration//GEN-END:variables
}
