/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ec.com.donbosquito.vista.moduloFactura;


import edu.ec.com.donbosquito.controlador.moduloFactura.ControladorLibroDetalle;
import edu.ec.com.donbosquito.controlador.moduloFactura.ControladorLibroDiario;
import edu.ec.com.donbosquito.modelo.moduloFactura.LibroDetalle;
import edu.ec.com.donbosquito.modelo.moduloFactura.LibroDiario;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexCT
 */
public class VistaLibroDiario extends javax.swing.JInternalFrame {

    /**
     * Creates new form LibroDiario
     */
    public VistaLibroDiario() {
        initComponents();
        rellenarLibroDiario();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTotalHaber = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalles = new javax.swing.JTable();
        lblTotalDebe = new javax.swing.JLabel();
        lblTotalHaberTexto = new javax.swing.JLabel();
        lblDescripcionTexto = new javax.swing.JLabel();
        lblTotalDebeTexto = new javax.swing.JLabel();
        lblEmpresaTexto = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblDetalles = new javax.swing.JLabel();

        setClosable(true);
        setTitle("LIBRO DIARIO");
        setMinimumSize(new java.awt.Dimension(0, 0));
        setName(""); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        lblTotalHaber.setBackground(new java.awt.Color(51, 51, 51));
        lblTotalHaber.setForeground(new java.awt.Color(0, 0, 102));
        lblTotalHaber.setText("Total Haber");
        jPanel1.add(lblTotalHaber);
        lblTotalHaber.setBounds(690, 410, 70, 16);

        tablaDetalles.setBackground(new java.awt.Color(255, 255, 255));
        tablaDetalles.setForeground(new java.awt.Color(0, 0, 0));
        tablaDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Detalles", "Debe", "Haber"
            }
        ));
        jScrollPane2.setViewportView(tablaDetalles);
        if (tablaDetalles.getColumnModel().getColumnCount() > 0) {
            tablaDetalles.getColumnModel().getColumn(0).setPreferredWidth(10);
            tablaDetalles.getColumnModel().getColumn(1).setPreferredWidth(350);
            tablaDetalles.getColumnModel().getColumn(2).setPreferredWidth(5);
            tablaDetalles.getColumnModel().getColumn(3).setPreferredWidth(5);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 150, 760, 220);

        lblTotalDebe.setBackground(new java.awt.Color(51, 51, 51));
        lblTotalDebe.setForeground(new java.awt.Color(0, 0, 102));
        lblTotalDebe.setText("Total Debe");
        jPanel1.add(lblTotalDebe);
        lblTotalDebe.setBounds(590, 410, 70, 16);

        lblTotalHaberTexto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotalHaberTexto.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblTotalHaberTexto);
        lblTotalHaberTexto.setBounds(690, 380, 90, 30);

        lblDescripcionTexto.setFont(new java.awt.Font("Dosis", 0, 18)); // NOI18N
        lblDescripcionTexto.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblDescripcionTexto);
        lblDescripcionTexto.setBounds(300, 80, 130, 30);

        lblTotalDebeTexto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotalDebeTexto.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblTotalDebeTexto);
        lblTotalDebeTexto.setBounds(590, 380, 90, 30);

        lblEmpresaTexto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblEmpresaTexto.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(lblEmpresaTexto);
        lblEmpresaTexto.setBounds(140, 20, 420, 60);

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexC\\Desktop\\search_50px.png")); // NOI18N
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar);
        btnBuscar.setBounds(120, 370, 50, 40);

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexC\\Desktop\\update.png")); // NOI18N
        btnUpdate.setBorderPainted(false);
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);
        btnUpdate.setBounds(430, 370, 50, 40);

        lblImagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexC\\Desktop\\libroDiario.png")); // NOI18N
        jPanel1.add(lblImagen);
        lblImagen.setBounds(570, -10, 230, 200);
        jPanel1.add(txtBuscar);
        txtBuscar.setBounds(30, 374, 90, 30);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);
        jButton1.setBounds(650, 220, 77, 32);

        btnMostrar.setBackground(new java.awt.Color(255, 255, 255));
        btnMostrar.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexC\\Desktop\\list_64px.png")); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrar);
        btnMostrar.setBounds(320, 370, 110, 40);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Ingrese Numero de Factura");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 410, 100, 10);

        lblDetalles.setBackground(new java.awt.Color(0, 0, 102));
        lblDetalles.setForeground(new java.awt.Color(51, 51, 51));
        lblDetalles.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel1.add(lblDetalles);
        lblDetalles.setBounds(10, 120, 790, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscarFactura();
        calcularValorDebe();
        calcularValorHaber();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        llenarTabla();
        calcularValorDebe();
        calcularValorHaber();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        llenarTabla();
        calcularValorDebe();
        calcularValorHaber();
    }//GEN-LAST:event_btnMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDescripcionTexto;
    private javax.swing.JLabel lblDetalles;
    private javax.swing.JLabel lblEmpresaTexto;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblTotalDebe;
    private javax.swing.JLabel lblTotalDebeTexto;
    private javax.swing.JLabel lblTotalHaber;
    private javax.swing.JLabel lblTotalHaberTexto;
    private javax.swing.JTable tablaDetalles;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    void rellenarLibroDiario() {

        ControladorLibroDiario conLibroDiario = new ControladorLibroDiario();
        LibroDiario libDiario = new LibroDiario();
        libDiario = conLibroDiario.buscarLibroDia(1);
        lblEmpresaTexto.setText(libDiario.getEmpresa());
        lblDescripcionTexto.setText(libDiario.getDescripcion());
        lblTotalDebeTexto.setText(String.valueOf(libDiario.getDebe()));
        lblTotalHaberTexto.setText(String.valueOf(libDiario.getHaber()));
    }

    void llenarTabla() {
        DecimalFormat decimales = new DecimalFormat("#.00");
        ControladorLibroDetalle controlLibroDetalle = new ControladorLibroDetalle();
        DefaultTableModel modelo = (DefaultTableModel) tablaDetalles.getModel();
        for (int i = 0; i < tablaDetalles.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
        for (LibroDetalle libroDetalle : controlLibroDetalle.listarLibroDetalle()) {
            Object[] rowData = {libroDetalle.getFecha(), libroDetalle.getDetalle(), decimales.format(libroDetalle.getDebe()).replace(",", "."), decimales.format(libroDetalle.getHaber()).replace(",", ".")};
            modelo.addRow(rowData);
        }
        tablaDetalles.setModel(modelo);

    }

    void buscarFactura() {
        DecimalFormat decimales = new DecimalFormat("#.00");
        ControladorLibroDetalle controlLibroDetalle = new ControladorLibroDetalle();
        DefaultTableModel modelo = (DefaultTableModel) tablaDetalles.getModel();
        for (int i = 0; i < tablaDetalles.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
        if (txtBuscar.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese una factura!");
        } else {
            for (LibroDetalle libroDetalle : controlLibroDetalle.buscarLibrosDetallesPorFactura(txtBuscar.getText())) {
                Object[] rowData = {libroDetalle.getFecha(), libroDetalle.getDetalle(), decimales.format(libroDetalle.getDebe()).replace(",", "."), libroDetalle.getHaber()};
                modelo.addRow(rowData);
            }
            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Detalles no encontrado, no se a registrado un pago en la factura " +txtBuscar.getText());
            }
            tablaDetalles.setModel(modelo);
            txtBuscar.setText("");
        }

    }

    void calcularValorDebe() {
        DecimalFormat decimales = new DecimalFormat("#.00");
        int datos = tablaDetalles.getRowCount();
        double suma = 0;
        for (int i = 0; i < datos; i++) {
            suma = suma + Double.parseDouble(tablaDetalles.getValueAt(i, 2).toString());
        }
        lblTotalDebeTexto.setText(String.valueOf(decimales.format(suma).replace(",", ".")));
    }

    void calcularValorHaber() {
        DecimalFormat decimales = new DecimalFormat("#.00");
        int datos = tablaDetalles.getRowCount();
        double suma = 0;
        for (int i = 0; i < datos; i++) {
            suma = suma + Double.parseDouble(tablaDetalles.getValueAt(i, 3).toString());
        }
        lblTotalHaberTexto.setText(String.valueOf(decimales.format(suma).replace(",", ".")));
    }
}
