/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ec.com.donbosquito.vista.moduloMatricula;

import edu.ec.com.donbosquito.controlador.moduloGrupo.ControladorGrupoCabecera;
import edu.ec.com.donbosquito.controlador.moduloMatricula.ControladorMatricula;

import edu.ec.com.donbosquito.controlador.moduloPersona.ControladorEstudiante;
import edu.ec.com.donbosquito.modelo.moduloGrupo.AnioLectivo;
import edu.ec.com.donbosquito.modelo.moduloGrupo.Curso;
import edu.ec.com.donbosquito.modelo.moduloGrupo.GrupoCabecera;
import edu.ec.com.donbosquito.modelo.moduloGrupo.Mension;
import edu.ec.com.donbosquito.modelo.moduloMatricula.Matricula;

import edu.ec.com.donbosquito.modelo.moduloPersona.Estudiante;
import edu.ec.com.donbosquito.modelo.moduloPersona.Persona;
import edu.ec.com.donbosquito.modelo.moduloPersona.Representante;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose pandiguana
 */
public class VistaMatricula extends javax.swing.JInternalFrame {

    private ControladorMatricula controladorMatricula ;
    private ControladorEstudiante controladorEstudiante;
    private ControladorGrupoCabecera controladorGrupoCabecera;
    private Matricula matricula;

    /**
     * Creates new form CrearMatriculas
     */
    public VistaMatricula(ControladorMatricula controladorMatricula, ControladorEstudiante controladorEstudiante, ControladorGrupoCabecera controladorGrupoCabecera) {
        initComponents();
        this.controladorMatricula =new ControladorMatricula();
        this.controladorEstudiante = new ControladorEstudiante();
        this.controladorGrupoCabecera = new ControladorGrupoCabecera();
        
        
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMatricula = new javax.swing.JPanel();
        matriculaJtabbedm = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txtMatriculaCodigo1 = new javax.swing.JTextField();
        codigoMatricualjL1 = new javax.swing.JLabel();
        fechaMatriculatxt1 = new javax.swing.JTextField();
        fechaMatricuaJbl1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        grupoCombo = new javax.swing.JComboBox<>();
        cedulajTextField1 = new javax.swing.JTextField();
        cedulaJlabel1 = new javax.swing.JLabel();
        nombrejTextField1 = new javax.swing.JTextField();
        nombrejLabel1 = new javax.swing.JLabel();
        apellidojLabel1 = new javax.swing.JLabel();
        direccionjLabel1 = new javax.swing.JLabel();
        telefonojLabel1 = new javax.swing.JLabel();
        correojLabel1 = new javax.swing.JLabel();
        fechaNacjLabel1 = new javax.swing.JLabel();
        edadjLabel1 = new javax.swing.JLabel();
        edadjTextField1 = new javax.swing.JTextField();
        fechaNajTextField1 = new javax.swing.JTextField();
        correojTextField1 = new javax.swing.JTextField();
        telefonojTextField1 = new javax.swing.JTextField();
        direccionjTextField1 = new javax.swing.JTextField();
        apellidojTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buscarBnt1 = new javax.swing.JButton();
        eliminarBnt1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        estudianteJlabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        listarMatriculasjScrollPane = new javax.swing.JScrollPane();
        matriculaLisJtbl = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cedulaJlabel2 = new javax.swing.JLabel();
        cedulajTextField2 = new javax.swing.JTextField();
        nombrejTextField2 = new javax.swing.JTextField();
        nombrejLabel2 = new javax.swing.JLabel();
        apellidojLabel2 = new javax.swing.JLabel();
        direccionjLabel2 = new javax.swing.JLabel();
        telefonojLabel2 = new javax.swing.JLabel();
        correojLabel2 = new javax.swing.JLabel();
        fechaNacjLabel2 = new javax.swing.JLabel();
        edadjLabel2 = new javax.swing.JLabel();
        edadjTextField2 = new javax.swing.JTextField();
        fechaNajTextField2 = new javax.swing.JTextField();
        correojTextField2 = new javax.swing.JTextField();
        telefonojTextField2 = new javax.swing.JTextField();
        direccionjTextField2 = new javax.swing.JTextField();
        apellidojTextField2 = new javax.swing.JTextField();
        codigoMatricualjL2 = new javax.swing.JLabel();
        txtMatriculaCodigo2 = new javax.swing.JTextField();
        fechaMatriculatxt2 = new javax.swing.JTextField();
        fechaMatricuaJbl2 = new javax.swing.JLabel();
        buscarBnt = new javax.swing.JButton();
        eliminarBnt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        estudianteJlabel2 = new javax.swing.JLabel();
        crearMatriculaPanel = new javax.swing.JPanel();
        txtMatriculaCodigo = new javax.swing.JTextField();
        fechaMatriculatxt = new javax.swing.JTextField();
        codigoMatricualjL = new javax.swing.JLabel();
        fechaMatricuaJbl = new javax.swing.JLabel();
        cedulaJlabel = new javax.swing.JLabel();
        nombrejLabel = new javax.swing.JLabel();
        apellidojLabel = new javax.swing.JLabel();
        direccionjLabel = new javax.swing.JLabel();
        telefonojLabel = new javax.swing.JLabel();
        correojLabel = new javax.swing.JLabel();
        fechaNacjLabel = new javax.swing.JLabel();
        cedulajTextField = new javax.swing.JTextField();
        nombrejTextField = new javax.swing.JTextField();
        fechaNajTextField = new javax.swing.JTextField();
        correojTextField = new javax.swing.JTextField();
        telefonojTextField = new javax.swing.JTextField();
        direccionjTextField = new javax.swing.JTextField();
        apellidojTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        estudianteJlabel = new javax.swing.JLabel();

        panelMatricula.setBackground(new java.awt.Color(31, 92, 150));

        matriculaJtabbedm.setBackground(new java.awt.Color(31, 92, 150));

        jPanel3.setLayout(null);
        jPanel3.add(txtMatriculaCodigo1);
        txtMatriculaCodigo1.setBounds(70, 20, 50, 30);

        codigoMatricualjL1.setText("Codigo");
        jPanel3.add(codigoMatricualjL1);
        codigoMatricualjL1.setBounds(10, 20, 70, 20);
        jPanel3.add(fechaMatriculatxt1);
        fechaMatriculatxt1.setBounds(200, 20, 220, 30);

        fechaMatricuaJbl1.setText("Fecha");
        jPanel3.add(fechaMatricuaJbl1);
        fechaMatricuaJbl1.setBounds(160, 20, 70, 30);

        jLabel3.setText("Grupo");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 400, 50, 16);

        grupoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(grupoCombo);
        grupoCombo.setBounds(130, 400, 230, 30);

        cedulajTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulajTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(cedulajTextField1);
        cedulajTextField1.setBounds(140, 110, 220, 22);

        cedulaJlabel1.setText("Cedula");
        jPanel3.add(cedulaJlabel1);
        cedulaJlabel1.setBounds(20, 110, 39, 16);
        jPanel3.add(nombrejTextField1);
        nombrejTextField1.setBounds(140, 140, 220, 22);

        nombrejLabel1.setText("Nombre");
        jPanel3.add(nombrejLabel1);
        nombrejLabel1.setBounds(20, 140, 50, 16);

        apellidojLabel1.setText("Apellido");
        jPanel3.add(apellidojLabel1);
        apellidojLabel1.setBounds(20, 170, 60, 16);

        direccionjLabel1.setText("Direccion");
        jPanel3.add(direccionjLabel1);
        direccionjLabel1.setBounds(20, 210, 60, 16);

        telefonojLabel1.setText("Telefono");
        jPanel3.add(telefonojLabel1);
        telefonojLabel1.setBounds(20, 240, 60, 16);

        correojLabel1.setText("Correo");
        jPanel3.add(correojLabel1);
        correojLabel1.setBounds(20, 270, 39, 16);

        fechaNacjLabel1.setText("Fecha Nacimiento");
        jPanel3.add(fechaNacjLabel1);
        fechaNacjLabel1.setBounds(20, 300, 110, 16);

        edadjLabel1.setText("Edad");
        jPanel3.add(edadjLabel1);
        edadjLabel1.setBounds(20, 330, 28, 16);

        edadjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadjTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(edadjTextField1);
        edadjTextField1.setBounds(140, 320, 220, 22);
        jPanel3.add(fechaNajTextField1);
        fechaNajTextField1.setBounds(140, 290, 220, 22);
        jPanel3.add(correojTextField1);
        correojTextField1.setBounds(140, 260, 220, 22);
        jPanel3.add(telefonojTextField1);
        telefonojTextField1.setBounds(140, 230, 220, 22);
        jPanel3.add(direccionjTextField1);
        direccionjTextField1.setBounds(140, 200, 220, 22);
        jPanel3.add(apellidojTextField1);
        apellidojTextField1.setBounds(140, 170, 220, 22);

        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 440, 410, 70);

        buscarBnt1.setText("Buscar");
        buscarBnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBnt1ActionPerformed(evt);
            }
        });
        jPanel3.add(buscarBnt1);
        buscarBnt1.setBounds(50, 460, 120, 40);

        eliminarBnt1.setText("Actualizar");
        eliminarBnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBnt1ActionPerformed(evt);
            }
        });
        jPanel3.add(eliminarBnt1);
        eliminarBnt1.setBounds(270, 460, 120, 40);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "codigo", "Grupo", "Descripcion"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(400, 90, 470, 320);

        estudianteJlabel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Estudiante"));
        jPanel3.add(estudianteJlabel1);
        estudianteJlabel1.setBounds(10, 70, 870, 320);

        matriculaJtabbedm.addTab("Actualizar", jPanel3);

        jPanel5.setLayout(null);

        matriculaLisJtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Fecha Matricula", "Estudiante", "Grupo"
            }
        ));
        listarMatriculasjScrollPane.setViewportView(matriculaLisJtbl);

        jPanel5.add(listarMatriculasjScrollPane);
        listarMatriculasjScrollPane.setBounds(0, 10, 880, 520);

        matriculaJtabbedm.addTab("Listar", jPanel5);

        jPanel4.setLayout(null);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox3);
        jComboBox3.setBounds(130, 390, 230, 30);

        jLabel4.setText("Grupo");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 400, 50, 16);

        cedulaJlabel2.setText("Cedula");
        jPanel4.add(cedulaJlabel2);
        cedulaJlabel2.setBounds(30, 90, 39, 16);

        cedulajTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulajTextField2ActionPerformed(evt);
            }
        });
        jPanel4.add(cedulajTextField2);
        cedulajTextField2.setBounds(150, 90, 220, 22);
        jPanel4.add(nombrejTextField2);
        nombrejTextField2.setBounds(150, 120, 220, 22);

        nombrejLabel2.setText("Nombre");
        jPanel4.add(nombrejLabel2);
        nombrejLabel2.setBounds(30, 120, 50, 16);

        apellidojLabel2.setText("Apellido");
        jPanel4.add(apellidojLabel2);
        apellidojLabel2.setBounds(30, 150, 60, 16);

        direccionjLabel2.setText("Direccion");
        jPanel4.add(direccionjLabel2);
        direccionjLabel2.setBounds(30, 190, 60, 16);

        telefonojLabel2.setText("Telefono");
        jPanel4.add(telefonojLabel2);
        telefonojLabel2.setBounds(30, 220, 60, 16);

        correojLabel2.setText("Correo");
        jPanel4.add(correojLabel2);
        correojLabel2.setBounds(30, 250, 39, 16);

        fechaNacjLabel2.setText("Fecha Nacimiento");
        jPanel4.add(fechaNacjLabel2);
        fechaNacjLabel2.setBounds(30, 280, 110, 16);

        edadjLabel2.setText("Edad");
        jPanel4.add(edadjLabel2);
        edadjLabel2.setBounds(30, 310, 28, 16);

        edadjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadjTextField2ActionPerformed(evt);
            }
        });
        jPanel4.add(edadjTextField2);
        edadjTextField2.setBounds(150, 300, 220, 22);
        jPanel4.add(fechaNajTextField2);
        fechaNajTextField2.setBounds(150, 270, 220, 22);
        jPanel4.add(correojTextField2);
        correojTextField2.setBounds(150, 240, 220, 22);
        jPanel4.add(telefonojTextField2);
        telefonojTextField2.setBounds(150, 210, 220, 22);
        jPanel4.add(direccionjTextField2);
        direccionjTextField2.setBounds(150, 180, 220, 22);
        jPanel4.add(apellidojTextField2);
        apellidojTextField2.setBounds(150, 150, 220, 22);

        codigoMatricualjL2.setText("Codigo");
        jPanel4.add(codigoMatricualjL2);
        codigoMatricualjL2.setBounds(10, 20, 70, 20);
        jPanel4.add(txtMatriculaCodigo2);
        txtMatriculaCodigo2.setBounds(70, 20, 50, 30);
        jPanel4.add(fechaMatriculatxt2);
        fechaMatriculatxt2.setBounds(200, 20, 220, 30);

        fechaMatricuaJbl2.setText("Fecha");
        jPanel4.add(fechaMatricuaJbl2);
        fechaMatricuaJbl2.setBounds(160, 20, 70, 30);

        buscarBnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ec/com/donbosquito/imagenes/Search Property_50px.png"))); // NOI18N
        buscarBnt.setText("Buscar");
        buscarBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBntActionPerformed(evt);
            }
        });
        jPanel4.add(buscarBnt);
        buscarBnt.setBounds(50, 460, 150, 50);

        eliminarBnt.setText("Eliminar");
        eliminarBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBntActionPerformed(evt);
            }
        });
        jPanel4.add(eliminarBnt);
        eliminarBnt.setBounds(270, 460, 120, 40);

        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel4.add(jLabel5);
        jLabel5.setBounds(30, 440, 410, 80);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "codigo", "Grupo", "Descripcion"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(400, 70, 470, 300);

        estudianteJlabel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Estudiante"));
        jPanel4.add(estudianteJlabel2);
        estudianteJlabel2.setBounds(10, 60, 870, 320);

        matriculaJtabbedm.addTab("Eliminar", jPanel4);

        crearMatriculaPanel.setLayout(null);
        crearMatriculaPanel.add(txtMatriculaCodigo);
        txtMatriculaCodigo.setBounds(70, 20, 50, 30);
        crearMatriculaPanel.add(fechaMatriculatxt);
        fechaMatriculatxt.setBounds(200, 20, 220, 30);

        codigoMatricualjL.setForeground(new java.awt.Color(25, 137, 196));
        codigoMatricualjL.setText("Codigo");
        crearMatriculaPanel.add(codigoMatricualjL);
        codigoMatricualjL.setBounds(10, 30, 70, 20);

        fechaMatricuaJbl.setForeground(new java.awt.Color(25, 137, 196));
        fechaMatricuaJbl.setText("Fecha");
        crearMatriculaPanel.add(fechaMatricuaJbl);
        fechaMatricuaJbl.setBounds(160, 20, 70, 30);

        cedulaJlabel.setForeground(new java.awt.Color(25, 137, 196));
        cedulaJlabel.setText("Cedula");
        crearMatriculaPanel.add(cedulaJlabel);
        cedulaJlabel.setBounds(10, 140, 39, 16);

        nombrejLabel.setForeground(new java.awt.Color(25, 137, 196));
        nombrejLabel.setText("Nombre");
        crearMatriculaPanel.add(nombrejLabel);
        nombrejLabel.setBounds(10, 170, 50, 16);

        apellidojLabel.setForeground(new java.awt.Color(25, 137, 196));
        apellidojLabel.setText("Apellido");
        crearMatriculaPanel.add(apellidojLabel);
        apellidojLabel.setBounds(10, 200, 60, 16);

        direccionjLabel.setForeground(new java.awt.Color(25, 137, 196));
        direccionjLabel.setText("Direccion");
        crearMatriculaPanel.add(direccionjLabel);
        direccionjLabel.setBounds(10, 240, 60, 16);

        telefonojLabel.setForeground(new java.awt.Color(25, 137, 196));
        telefonojLabel.setText("Telefono");
        crearMatriculaPanel.add(telefonojLabel);
        telefonojLabel.setBounds(10, 270, 60, 16);

        correojLabel.setForeground(new java.awt.Color(25, 137, 196));
        correojLabel.setText("Correo");
        crearMatriculaPanel.add(correojLabel);
        correojLabel.setBounds(10, 300, 39, 16);

        fechaNacjLabel.setForeground(new java.awt.Color(25, 137, 196));
        fechaNacjLabel.setText("Fecha Nacimiento");
        crearMatriculaPanel.add(fechaNacjLabel);
        fechaNacjLabel.setBounds(10, 330, 110, 16);

        cedulajTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulajTextFieldActionPerformed(evt);
            }
        });
        crearMatriculaPanel.add(cedulajTextField);
        cedulajTextField.setBounds(130, 140, 220, 22);
        crearMatriculaPanel.add(nombrejTextField);
        nombrejTextField.setBounds(130, 170, 220, 22);
        crearMatriculaPanel.add(fechaNajTextField);
        fechaNajTextField.setBounds(130, 320, 220, 22);
        crearMatriculaPanel.add(correojTextField);
        correojTextField.setBounds(130, 290, 220, 22);
        crearMatriculaPanel.add(telefonojTextField);
        telefonojTextField.setBounds(130, 260, 220, 22);
        crearMatriculaPanel.add(direccionjTextField);
        direccionjTextField.setBounds(130, 230, 220, 22);
        crearMatriculaPanel.add(apellidojTextField);
        apellidojTextField.setBounds(130, 200, 220, 22);

        jButton1.setBackground(new java.awt.Color(31, 92, 150));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ec/com/donbosquito/imagenes/Save_50px.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        crearMatriculaPanel.add(jButton1);
        jButton1.setBounds(710, 410, 150, 60);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un grupo" }));
        jComboBox1.setToolTipText("");
        crearMatriculaPanel.add(jComboBox1);
        jComboBox1.setBounds(130, 380, 220, 22);

        jLabel2.setForeground(new java.awt.Color(25, 137, 196));
        jLabel2.setText("Grupo");
        crearMatriculaPanel.add(jLabel2);
        jLabel2.setBounds(20, 390, 34, 16);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "codigo", "Grupo", "Descripcion"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        crearMatriculaPanel.add(jScrollPane3);
        jScrollPane3.setBounds(400, 90, 470, 320);

        estudianteJlabel.setBackground(new java.awt.Color(31, 92, 150));
        estudianteJlabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        crearMatriculaPanel.add(estudianteJlabel);
        estudianteJlabel.setBounds(0, 70, 880, 410);

        matriculaJtabbedm.addTab("Crear Matricula", crearMatriculaPanel);

        javax.swing.GroupLayout panelMatriculaLayout = new javax.swing.GroupLayout(panelMatricula);
        panelMatricula.setLayout(panelMatriculaLayout);
        panelMatriculaLayout.setHorizontalGroup(
            panelMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(matriculaJtabbedm, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
        );
        panelMatriculaLayout.setVerticalGroup(
            panelMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMatriculaLayout.createSequentialGroup()
                .addComponent(matriculaJtabbedm, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBntActionPerformed
        /*  if(JOptionPane.showConfirmDialog(this, "¿Desea realmente eliminar la Factura?", "Eliminar Factura", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            eliminarFacturaDetalle();
            eliminarFactura();
            limpiarTablaDetalle();
            limpiarTablaFactura();
            JOptionPane.showMessageDialog(this, "Factura Eiminada");
            nFacturaTxt.setText("");
            eliminarBnt.setEnabled(false);
        }*/
        eliminarMatricula();
    }//GEN-LAST:event_eliminarBntActionPerformed

    private void buscarBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBntActionPerformed
        /*
        if(nFacturaTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese el código de la Factura");
            eliminarBnt.setEnabled(false);
        }else{
            buscarFactura();
            listarDetalle();
            eliminarBnt.setEnabled(true);
        }
         */
    }//GEN-LAST:event_buscarBntActionPerformed

    private void edadjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadjTextField2ActionPerformed

    private void cedulajTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulajTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulajTextField2ActionPerformed

    private void eliminarBnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBnt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarBnt1ActionPerformed

    private void buscarBnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBnt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarBnt1ActionPerformed

    private void edadjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadjTextField1ActionPerformed

    private void cedulajTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulajTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulajTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        crearMatricula();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cedulajTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulajTextFieldActionPerformed
        // TODO add your handling code here:

        buscarEstudiante();
    }//GEN-LAST:event_cedulajTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidojLabel;
    private javax.swing.JLabel apellidojLabel1;
    private javax.swing.JLabel apellidojLabel2;
    private javax.swing.JTextField apellidojTextField;
    private javax.swing.JTextField apellidojTextField1;
    private javax.swing.JTextField apellidojTextField2;
    private javax.swing.JButton buscarBnt;
    private javax.swing.JButton buscarBnt1;
    private javax.swing.JLabel cedulaJlabel;
    private javax.swing.JLabel cedulaJlabel1;
    private javax.swing.JLabel cedulaJlabel2;
    private javax.swing.JTextField cedulajTextField;
    private javax.swing.JTextField cedulajTextField1;
    private javax.swing.JTextField cedulajTextField2;
    private javax.swing.JLabel codigoMatricualjL;
    private javax.swing.JLabel codigoMatricualjL1;
    private javax.swing.JLabel codigoMatricualjL2;
    private javax.swing.JLabel correojLabel;
    private javax.swing.JLabel correojLabel1;
    private javax.swing.JLabel correojLabel2;
    private javax.swing.JTextField correojTextField;
    private javax.swing.JTextField correojTextField1;
    private javax.swing.JTextField correojTextField2;
    private javax.swing.JPanel crearMatriculaPanel;
    private javax.swing.JLabel direccionjLabel;
    private javax.swing.JLabel direccionjLabel1;
    private javax.swing.JLabel direccionjLabel2;
    private javax.swing.JTextField direccionjTextField;
    private javax.swing.JTextField direccionjTextField1;
    private javax.swing.JTextField direccionjTextField2;
    private javax.swing.JLabel edadjLabel1;
    private javax.swing.JLabel edadjLabel2;
    private javax.swing.JTextField edadjTextField1;
    private javax.swing.JTextField edadjTextField2;
    private javax.swing.JButton eliminarBnt;
    private javax.swing.JButton eliminarBnt1;
    private javax.swing.JLabel estudianteJlabel;
    private javax.swing.JLabel estudianteJlabel1;
    private javax.swing.JLabel estudianteJlabel2;
    private javax.swing.JLabel fechaMatricuaJbl;
    private javax.swing.JLabel fechaMatricuaJbl1;
    private javax.swing.JLabel fechaMatricuaJbl2;
    private javax.swing.JTextField fechaMatriculatxt;
    private javax.swing.JTextField fechaMatriculatxt1;
    private javax.swing.JTextField fechaMatriculatxt2;
    private javax.swing.JLabel fechaNacjLabel;
    private javax.swing.JLabel fechaNacjLabel1;
    private javax.swing.JLabel fechaNacjLabel2;
    private javax.swing.JTextField fechaNajTextField;
    private javax.swing.JTextField fechaNajTextField1;
    private javax.swing.JTextField fechaNajTextField2;
    private javax.swing.JComboBox<String> grupoCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JScrollPane listarMatriculasjScrollPane;
    private javax.swing.JTabbedPane matriculaJtabbedm;
    private javax.swing.JTable matriculaLisJtbl;
    private javax.swing.JLabel nombrejLabel;
    private javax.swing.JLabel nombrejLabel1;
    private javax.swing.JLabel nombrejLabel2;
    private javax.swing.JTextField nombrejTextField;
    private javax.swing.JTextField nombrejTextField1;
    private javax.swing.JTextField nombrejTextField2;
    private javax.swing.JPanel panelMatricula;
    private javax.swing.JLabel telefonojLabel;
    private javax.swing.JLabel telefonojLabel1;
    private javax.swing.JLabel telefonojLabel2;
    private javax.swing.JTextField telefonojTextField;
    private javax.swing.JTextField telefonojTextField1;
    private javax.swing.JTextField telefonojTextField2;
    private javax.swing.JTextField txtMatriculaCodigo;
    private javax.swing.JTextField txtMatriculaCodigo1;
    private javax.swing.JTextField txtMatriculaCodigo2;
    // End of variables declaration//GEN-END:variables

    void buscarEstudiante() {

        Persona persona = new Persona(0, "", "", "", "", "", "") {
        };
        Estudiante estudiante = controladorEstudiante.buscarCedulaEstudiante(cedulajTextField.getText());
        nombrejTextField.setText(String.valueOf(estudiante.getCedula()));
        apellidojTextField.setText(estudiante.getNombre());
        direccionjTextField.setText(estudiante.getDireccion());
        telefonojTextField.setText(estudiante.getTelefono());
        correojTextField.setText(estudiante.getCorreo());

    }

    void crearMatricula() {
        Persona persona = new Persona(0, "", "", "", "", "", "") {
        };
        Representante representante = new Representante(0, "", persona, PROPERTIES, "", "", "", "", "", "");
        Estudiante estudiante = new Estudiante(0, ParseFecha("0/0/0"), WIDTH, ParseFecha("0/0/0"), persona, representante, PROPERTIES, "", "", "", "", "", "");
        Curso curso = new Curso(0, "", "");
        AnioLectivo anioLectivo = new AnioLectivo(0, "", ParseFecha("0/0/0"), ParseFecha("0/0/0"));
        Mension mension = new Mension(0, "", "", "");
        GrupoCabecera grupoCabecera = new GrupoCabecera(0, "", "", "", curso, anioLectivo, mension);

        matricula = new Matricula(0, ParseFecha("0/0/0"), estudiante, grupoCabecera);

        controladorMatricula = new ControladorMatricula();
        matricula.setCodigo(Integer.valueOf(txtMatriculaCodigo1.getText()));
        //matricula.setFechaMatricula(fechaMatriculatxt1.getText());
        matricula.setEstudiante((Estudiante) controladorEstudiante.buscarCedulaEstudiante(cedulajTextField1.getText()));
        // matricula.setGrupoCabecera((GrupoCabecera)controladorGrupoCabecera.buscarGrupoCabeceraCodigo(grupoCombo.gett));
        controladorMatricula.crearMatricula(matricula);

    }

    void eliminarMatricula() {
        Persona persona = new Persona(0, "", "", "", "", "", "") {
        };
        Representante representante = new Representante(0, "", persona, PROPERTIES, "", "", "", "", "", "");
        Estudiante estudiante = new Estudiante(0, ParseFecha("0/0/0"), WIDTH, ParseFecha("0/0/0"), persona, representante, PROPERTIES, "", "", "", "", "", "");
        Curso curso = new Curso(0, "", "");
        AnioLectivo anioLectivo = new AnioLectivo(0, "", ParseFecha("0/0/0"), ParseFecha("0/0/0"));
        Mension mension = new Mension(0, "", "", "");
        GrupoCabecera grupoCabecera = new GrupoCabecera(0, "", "", "", curso, anioLectivo, mension);
        //    matriculaJtabbedm = new Matricula(0, ParseFecha("0/0/0"), estudiante, grupoCabecera);
        matricula = new Matricula(0, ParseFecha("0/0/0"), estudiante, grupoCabecera);
        matricula.setCodigo(matricula.getCodigo());

    }

    void listarMatricula() {
        DefaultTableModel modelo = (DefaultTableModel) matriculaLisJtbl.getModel();
        for (int i = 0; i < matriculaLisJtbl.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;

        }
        for (Matricula j : controladorMatricula.listarMatriculas()) {
            Object[] rowData = {j.getCodigo(), j.getFechaMatricula(), j.getEstudiante(), j.getGrupoCabecera()};
            modelo.addRow(rowData);

        }
        matriculaLisJtbl.setModel(modelo);
    }
/*
    void buscarMatricula() {

        Persona persona = new Persona(0, "", "", "", "", "", "") {
        };
        Representante representante = new Representante(0, "", persona, 0, "", "", "", "", "", "");
        Estudiante estudiante = new Estudiante(0, ParseFecha("0/0/0"), 0, ParseFecha("0/0/0"), persona, representante, 0, "", "", "", "", "", "");
        Curso curso = new Curso(0, "", "");
        AnioLectivo anioLectivo = new AnioLectivo(0, "", ParseFecha("0/0/0"), ParseFecha("0/0/0"));
        Mension mension = new Mension(0, "", "", "");
        GrupoCabecera grupoCabecera = new GrupoCabecera(0, "", "", "", curso, anioLectivo, mension);
        Matricula matriculas = new Matricula(0, ParseFecha("0/0/0"), estudiante, grupoCabecera);
        matriculas = controladorMatricula.buscarMatriculaCodigo(txtMatriculaCodigo2.getText());
        txtMatriculaCodigo2.setText(matricula.getCodigo());
        fechaMatricuaJbl2.setText(matricula.getFechaMatricula());

        grupoCabecera = controladorGrupoCabecera.buscarGrupoCabecera(txtBuscarGrupoCabecera.getText());
       

    }
    */

    public static Date ParseFecha(String fecha) {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaDate = null;
        try {
            fechaDate = formato.parse(fecha);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        return fechaDate;
    }
}
