/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ec.com.donbosquito.vista.moduloCalificaciones;

/**
 *
 * @author Bryam
 */
public class Calificaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form Calificaciones
     */
    public Calificaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jlBuscarModificarCedula = new javax.swing.JLabel();
        txtBuscarCedulaModificarEstudiante = new javax.swing.JTextField();
        jbBuscarModificarEstudiante = new javax.swing.JButton();
        jlCedulaModificarEstudiante = new javax.swing.JLabel();
        txtCedulaModificarEstudiante = new javax.swing.JTextField();
        jlNombreModificarEstudiante = new javax.swing.JLabel();
        txtNombreModificarEstudiante = new javax.swing.JTextField();
        jLApellidosModificarEstudiante = new javax.swing.JLabel();
        txtApellidosModificarEstudiante = new javax.swing.JTextField();
        txtEdadModificarEstudiante = new javax.swing.JTextField();
        jlEdadModificarEstudiante = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Calificaciones");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jlBuscarModificarCedula.setForeground(new java.awt.Color(204, 204, 204));
        jlBuscarModificarCedula.setText("Ingresar Cédula Estudiante:");

        txtBuscarCedulaModificarEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        jbBuscarModificarEstudiante.setBackground(new java.awt.Color(51, 51, 51));
        jbBuscarModificarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jbBuscarModificarEstudiante.setText("Buscar");
        jbBuscarModificarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarModificarEstudianteActionPerformed(evt);
            }
        });

        jlCedulaModificarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlCedulaModificarEstudiante.setText("Cédula:");

        txtCedulaModificarEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        jlNombreModificarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlNombreModificarEstudiante.setText("Nombre:");

        txtNombreModificarEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        jLApellidosModificarEstudiante.setBackground(new java.awt.Color(204, 204, 204));
        jLApellidosModificarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jLApellidosModificarEstudiante.setText("Apellidos:");

        txtApellidosModificarEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        txtEdadModificarEstudiante.setBackground(new java.awt.Color(153, 153, 153));

        jlEdadModificarEstudiante.setForeground(new java.awt.Color(204, 204, 204));
        jlEdadModificarEstudiante.setText("Edad:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCedulaModificarEstudiante)
                            .addComponent(jlNombreModificarEstudiante)
                            .addComponent(jLApellidosModificarEstudiante)
                            .addComponent(jlEdadModificarEstudiante))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreModificarEstudiante)
                            .addComponent(txtApellidosModificarEstudiante)
                            .addComponent(txtEdadModificarEstudiante)
                            .addComponent(txtCedulaModificarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(txtBuscarCedulaModificarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jbBuscarModificarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jlBuscarModificarCedula)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlBuscarModificarCedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarCedulaModificarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscarModificarEstudiante))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCedulaModificarEstudiante)
                            .addComponent(txtCedulaModificarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNombreModificarEstudiante)
                            .addComponent(txtNombreModificarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLApellidosModificarEstudiante)
                            .addComponent(txtApellidosModificarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdadModificarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlEdadModificarEstudiante))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Calificaciones", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarModificarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarModificarEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbBuscarModificarEstudianteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLApellidosModificarEstudiante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbBuscarModificarEstudiante;
    private javax.swing.JLabel jlBuscarModificarCedula;
    private javax.swing.JLabel jlCedulaModificarEstudiante;
    private javax.swing.JLabel jlEdadModificarEstudiante;
    private javax.swing.JLabel jlNombreModificarEstudiante;
    private javax.swing.JTextField txtApellidosModificarEstudiante;
    private javax.swing.JTextField txtBuscarCedulaModificarEstudiante;
    private javax.swing.JTextField txtCedulaModificarEstudiante;
    private javax.swing.JTextField txtEdadModificarEstudiante;
    private javax.swing.JTextField txtNombreModificarEstudiante;
    // End of variables declaration//GEN-END:variables
}
